### ISSUE TITLE
Chat bubbles not working

### ISSUE THREAD

**Issue by LimitedCause** [Haleth/Aurora#101]
I tried disabling everything else and resetting ui. but the auroras chat bubble skin wont work.

**Comment by Gethe** [comment]
Are you in an instance? Chat bubble can't be skinned in instances.

**Comment by LimitedCause** [comment]
Oh that makes sense, i was in ICC. Cheers!

2018-01-12 4:03 GMT+02:00 Tim West <notifications@github.com>:
