### ISSUE TITLE
Bagsbar tinted dark

### ISSUE THREAD

**Issue by TalasNetrag** [Haleth/Aurora#102]
The Bagsbar is tinted darker with Aurora enabled (not the inventory).
<a href="http://www.directupload.net/file/d/4970/86evxxmb_jpg.htm" target="_blank"><img src="http://fs1.directupload.net/images/180117/temp/86evxxmb.jpg" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>
Edit: This issue comes up when Aurora and Masque are activated. Aurora v7.3.0.5 doesnt have this issue.

**Comment by TalasNetrag** [comment]
Yes, I'm using Bagnon but it doesnt seem to be related to the issue.
I've tested further combinations and it seems the combination of Aurora + Bartender4 + Masque is causing this.
Aurora + Bagnon + Masque is ok.

**Comment by hungry** [comment]
Having the same issue, even with Aurora being the only enabled addon

**Comment by Gethe** [comment]
Should be fixed with latest release
