### ISSUE TITLE
Inventory background is black

### ISSUE THREAD

**Issue by TalasNetrag** [Haleth/Aurora#103]
With Auroras bag skinning enabled the inventory background is pitch black.
<a href="http://www.directupload.net/file/d/4970/xkvsavpq_jpg.htm" target="_blank"><img src="http://fs1.directupload.net/images/180117/temp/xkvsavpq.jpg" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>
Screenshot taken with Aurora as the only AddOn enabled.

**Comment by Gethe** [comment]
Fixed with latest release
