### ISSUE TITLE
Blizzard Token lua error

### ISSUE THREAD

**Issue by Sajira88** [Haleth/Aurora#105]
![wowscrnshot_012018_172032](https://user-images.githubusercontent.com/35633756/35185528-45113eb4-fe06-11e7-9068-1c5b27a4c7d4.jpg)
Greetings, been having the lua error for Blizzard_TokenLua since of today, the client is updated and so are the addons so not sure what is going on. 

Kind regards, Sajira88

**Comment by Gethe** [comment]
This error is not frame Aurora

**Comment by Sajira88** [comment]
Then why is it labeled under Aurora if i dig deeper?

**Comment by Gethe** [comment]
if that's the case, please post the full error in text instead of in a screenshot.
