### ISSUE TITLE
dropping frame rates

### ISSUE THREAD

**Issue by casper69** [Haleth/Aurora#106]
when i have aurora enabled i can be sitting still and fps is all over the place. if i disable it then all fps stays the same any ideas?

**Comment by Gethe** [comment]
This is not something i've experienced, so I can't say what might be causing it. Have you tried with only Aurora enabled?

**Comment by casper69** [comment]
yes i have and i get the fps issues when i do. without it no fps and skip issues

**Comment by casper69** [comment]
guess ill just have to have all my accts go to elvui

**Comment by casper69** [comment]
but whats got me baffled is thier has got to be some kind of update or patch that can be brought in to fix it. ive spent hours with elvui and am still not satisfied

**Comment by Gethe** [comment]
I'm sure there is a fix for it, but not being able to replicate it makes finding that fix near impossible.

**Comment by casper69** [comment]
lol i can replicate it all day

**Comment by casper69** [comment]
i have posted all the errors in a link im pretty sure its fps#107

**Comment by Gethe** [comment]
*You* may be able to replicate it, but *I* can't. Which means that any attempt at fixing it would be a shot in the dark.

**Comment by Gethe** [comment]
I saw the errors you posted in issue #107. They are caused by AltzUI, not Aurora. Please see the comment i made on that issue.

If your replication of this issue involves those errors, please disable AltzUI and see if they still happen and if the frame rate issue still persists.

**Comment by casper69** [comment]
I did I only had aurora running and the fps would still happen but when I
had it disabled it would stop
