### ISSUE TITLE
4 errors

### ISSUE THREAD

**Issue by casper69** [Haleth/Aurora#107]
1.... Message: ...ce\AddOns\AltzUIConfig\lib\UIDropDownMenu\Aurora.lua:5: attempt to index field 'classcolours' (a nil value)
Time: 01/22/18 19:37:20
Count: 1
Stack: ...ce\AddOns\AltzUIConfig\lib\UIDropDownMenu\Aurora.lua:5: attempt to index field 'classcolours' (a nil value)
[C]: ?
...ce\AddOns\AltzUIConfig\lib\UIDropDownMenu\Aurora.lua:5: in main chunk

Locals: 

2.....Message: Interface\AddOns\AltzUIConfig\api.lua:493: bad argument #1 to 'unpack' (table expected, got nil)
Time: 01/22/18 19:37:20
Count: 1
Stack: Interface\AddOns\AltzUIConfig\api.lua:493: bad argument #1 to 'unpack' (table expected, got nil)
[C]: ?
[C]: in function `unpack'
Interface\AddOns\AltzUIConfig\api.lua:493: in main chunk

Locals: 

3...Message: Interface\AddOns\AltzUIConfig\gui.lua:215: attempt to call field 'createmultilinebox' (a nil value)
Time: 01/22/18 19:37:20
Count: 1
Stack: Interface\AddOns\AltzUIConfig\gui.lua:215: attempt to call field 'createmultilinebox' (a nil value)
[C]: in function `createmultilinebox'
Interface\AddOns\AltzUIConfig\gui.lua:215: in main chunk

Locals: 

4...Message: Interface\AddOns\Aurora\Skin\api.lua:543: arrowdown is not a registered texture.
Time: 01/22/18 19:37:20
Count: 1
Stack: Interface\AddOns\Aurora\Skin\api.lua:543: arrowdown is not a registered texture.
[C]: ?
[C]: in function `assert'
Interface\AddOns\Aurora\Skin\api.lua:543: in function <Interface\AddOns\Aurora\Skin\api.lua:541>
Interface\AddOns\Aurora\Skin\init.lua:63: in function `SetTexture'
Interface\AddOns\Aurora\Skin\deprecated.lua:240: in function `CreateArrow'
Interface\AddOns\Aurora\Skin\deprecated.lua:255: in function `ReskinArrow'
Interface\AddOns\AltzUI\mods\tweaks\watchframe.lua:17: in main chunk

Locals:

**Comment by Gethe** [comment]
AltzUI seems to use it's own fork of Aurora which has diverged from this repo. I would either contact the maintainers for AltzUI and ask them to start using the mainline Aurora, or you could switch back to the version that they package with the UI.
