### ISSUE TITLE
Aurora + ElvUI

### ISSUE THREAD

**Issue by MaartenBl** [Haleth/Aurora#109]
Got some issues with the tooltip icons in the Dungeon Journal dissapearing when Aurora is enabled. Together with the set appearances in the collections tab.

Also there's another issue with the chat bubbles, they don't seem to work correctly when in the Death Knight Order Hall (Give "Ebon Knight" instead of player name). Also curious why the chat bubbles don't work in instances.

**Comment by Gethe** [comment]
If your using Aurora with ElvUI there may be a conflict there as ElvUI has its own built-in UI skin. Are you getting any errors?

As for chat bubbles in instances, see issue #101
