### ISSUE TITLE
Gossip Frame Text Color

### ISSUE THREAD

**Issue by cipher3010** [Haleth/Aurora#115]
In GossipFrame. Some Text is not clear.
![image](https://user-images.githubusercontent.com/37508802/37567070-6fe6a520-2afc-11e8-9306-083a27560d43.png)

I add some code to fix it.But I'm not sure, I write it in correct code session.
In  Skin\FrameXML\GossipFrame.lua
           function private.FrameXML.GossipFrame()
After _G.GossipGreetingScrollFrameMiddle:Hide() 
Add this code 
	local r, g, b = Aurora.highlightColor:GetRGB()
	_G.GossipGreetingText:SetTextColor(r, g, b)

![image](https://user-images.githubusercontent.com/37508802/37567156-c1161240-2afd-11e8-9702-bffe81648ec2.png)

**Comment by Gethe** [comment]
What version are you using?

**Comment by Gethe** [comment]
There have been some updates to this frame in the latest release. If you're still seeing this after updating, please reopen this issue with more detail.
