### ISSUE TITLE
Scenario objective progress bar disappears

### ISSUE THREAD

**Issue by IMM3612** [Haleth/Aurora#116]
The progress bar under scenario objective (Argus Invasions Stage 1 percentage, Garrison Invasion timer) is there at the start but then quickly disappears. Issue present with all other addons disabled.
![Aurora disabled](https://i.imgur.com/DPxy3VY.jpg)
![Aurora enabled](https://i.imgur.com/hO08O4z.jpg)
![Frame inspect](https://i.imgur.com/W6yahPc.jpg)

**Comment by MisterT87** [comment]
Tested it today with newest Aurora version from curse (v.8.0.1.0-15-g2571db1) - bug is still available in this version

**Comment by Gethe** [comment]
I'll close this issue when I get a chance to test and fix it.
