### ISSUE TITLE
pet switching at stable broken for hunters

### ISSUE THREAD

**Issue by Arthas2k** [Haleth/Aurora#117]
### Prerequisites ###

* [ ] Are you running the [latest release of Aurora](https://github.com/Haleth/Aurora/releases)? If you're using the Twitch updater, make sure the release type is set to "Release" unless told otherwise.
* [ ] Did you [perform a cursory search](https://github.com/Haleth/Aurora/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?

### Description ###

[Short description of problem here]

### Steps to Reproduce ###

1. [First Step] Enable Aurora
2. [Second Step] use hunter stable
3. [Other Steps...] broken

**Expected behavior:**

i expect to be able to use the stable with Aurora enabled but this isnt the case

**Actual behavior:**

stable cant change pets unless Aurora is deactivated

``` lua
-- If you recived an error, place it here.
```

``` lua
-- Separate them if you have more than one.
```

### Additional information ###

* Problem started happening recently, didn't happen in an older version of Aurora: [Yes/No] not sure
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] yes

**Screenshots and GIFs**

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

**Installed AddOns:**

[List of installed addons which may conflict with the Aurora skin]

**Comment by Gethe** [comment]
Thanks for the report. If you're going to use the alpha version please say so in the report, otherwise you should revert back to the release version.
