### ISSUE TITLE
Vendor Windows not getting changed and Mission Board Tab Buttons misaligned

### ISSUE THREAD

**Issue by Grandorg** [Haleth/Aurora#118]
### Prerequisites ###

* [x] Are you running the [latest release of Aurora](https://github.com/Haleth/Aurora/releases)? If you're using the Twitch updater, make sure the release type is set to "Release" unless told otherwise.
* [x] Did you [perform a cursory search](https://github.com/Haleth/Aurora/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?

### Description ###

Vendor Windows Frames are not getting properly changed since the newest Version of the Add On. 
![ss 2018-05-28 at 12 08 29](https://user-images.githubusercontent.com/18095367/40591138-c43f77a0-620b-11e8-80eb-465299341f8b.png)

Seccond issue is on the Orderhall Mission Window. The Buttons for Missions and Follower are misaligned.
![ss 2018-05-28 at 12 18 53](https://user-images.githubusercontent.com/18095367/40591246-c3eac3ac-620d-11e8-8940-8e32db9ca518.png)

### Steps to Reproduce ###

1. [First Step] Installing newest Version (v8.0.1.0)
2. [Second Step] Starting the Game and talking to a Vendor
3. [Other Steps...] Using the Mission Board in any Orderhall.

### Additional information ###

* Problem started happening recently, didn't happen in an older version of Aurora: [Yes/No] YES
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] YES

**Comment by Gethe** [comment]
I'm not seeing an issue with the vendor frame. Do you have any addons that affect the vendor frame like TSM?
![image](https://i.imgur.com/KFF1pVQ.png)


The garrison tabs are a bit more complicated than most tabbed UI frames. Still figuring out a good solution.

**Comment by Grandorg** [comment]
yeah i have TSM 3 installed. Main for selling quickly all the junk.
