### ISSUE TITLE
Green backround in tooltips and not compatible with angry keystones addon

### ISSUE THREAD

**Issue by MisterT87** [Haleth/Aurora#120]
Hey Guys and thanks for the great work...

With the newest aurora (Version 8.0.1.0) I got 2 problems:
- I have tooltips with green backround on the worldmap
- I think compability is lost since newest version ? -> If I am in mythic+ dungeon (with Angry Keystones addon activated) - I didnt see the enemy forces Bar (also didnt see the percentage).
I only see Enemy Forces text. 

greetings

**Comment by Krustensusi** [comment]
same problem here.

**Comment by MisterT87** [comment]
Tested newest version: v8.0.1.0-11-gb470e9a

the green tooltips are gone and fixed but not the mythic+ enemy forces bug...

If I starting a mythic plus key, the progress bar of enemy forces shown up for 1-2 seconds and then its gone (didnt see it anymore)

See screenshot:
![mythicplus](https://user-images.githubusercontent.com/11234038/40867875-145d900a-6608-11e8-894f-64a61ed694dd.png)

Steps to reproduce:
- Disabled all addons except aurora itself
- joined a mythic+ dungen
- started my mythic+ Keystone
- disabled aurora addon during the run and the problem is gone

Others: Didnt see any other lua errors...

**Comment by Krustensusi** [comment]
there is the same issue with the "daily global check" addon.
