### ISSUE TITLE
Enemy forces bar in mythic+ dungeons not shown in newest beta anyway

### ISSUE THREAD

**Issue by MisterT87** [Haleth/Aurora#121]
Tested newest version: v8.0.1.0-11-gb470e9a

the green tooltips are gone and fixed but not the mythic+ enemy forces bug...

If I starting a mythic plus key, the progress bar of enemy forces shown up for 1-2 seconds and then its gone (didnt see it anymore)

See screenshot:
![mythicplus](https://user-images.githubusercontent.com/11234038/40867875-145d900a-6608-11e8-894f-64a61ed694dd.png)

Steps to reproduce:
- Disabled all addons except aurora itself
- joined a mythic+ dungen
- started my mythic+ Keystone
- disabled aurora addon during the run and the problem is gone

Others: Didnt see any other lua errors...

continuation of Issue [#120](https://github.com/Haleth/Aurora/issues/120)

**Comment by Gethe** [comment]
This is likely the same as issue #116
