### ISSUE TITLE
old bugs back again / most of the windows not skinned by aurora 8.0.1.1

### ISSUE THREAD

**Issue by MisterT87** [Haleth/Aurora#125]
Hi,
Installed newest release version (v8.0.1.1) and the most of old bugs are back again (i.e. green tooltips).
Also a lot (not all) windows are not skinned anymore by aurora
See screenshots below:

Aurora acivated:
![wowscrnshot_062418_200501](https://user-images.githubusercontent.com/11234038/41822137-553c3eba-77eb-11e8-999c-041e76d2467f.jpg)

Green Tooltip bug:
![wowscrnshot_062418_200944](https://user-images.githubusercontent.com/11234038/41822140-5f34e458-77eb-11e8-838c-66db7149167a.jpg)

Here u see the Windows not skinned by Aurora (not all windows tested!):
Talent tree window:
![wowscrnshot_061218_130111](https://user-images.githubusercontent.com/11234038/41822154-8743a4e8-77eb-11e8-8506-a822cd78e862.jpg)

Order Hall Missions window:
![wowscrnshot_062418_200444](https://user-images.githubusercontent.com/11234038/41822157-9193fcea-77eb-11e8-842c-669a997d9d24.jpg)

Mail window:
![wowscrnshot_062418_200452](https://user-images.githubusercontent.com/11234038/41822162-9efcaa44-77eb-11e8-9dd7-812b125e366f.jpg)

Friend window:
![wowscrnshot_062418_200600](https://user-images.githubusercontent.com/11234038/41829290-2a60a858-783a-11e8-873d-3f1a518181e6.jpg)

NPC Window:
![wowscrnshot_062418_200705](https://user-images.githubusercontent.com/11234038/41822168-b3dc3b3c-77eb-11e8-8c2d-a448d9dadc47.jpg)

Dungeon finder:
![wowscrnshot_062418_200749](https://user-images.githubusercontent.com/11234038/41822180-bfe6dd56-77eb-11e8-964b-b6103523a5e8.jpg)

World Map:
![wowscrnshot_062418_200933](https://user-images.githubusercontent.com/11234038/41822182-c8a902a2-77eb-11e8-9aef-d18fa513bdf5.jpg)

NOTE1: I am using Aurora missing textures (from wowinterface) thats why my windows are black anyway - its not from aurora!
NOTE2: latest fully working aurora release (tested last alpha release also): v8.0.1.0-24-gba31a98

**Comment by Gethe** [comment]
I'm not seeing any of this. Are you getting any errors?

**Comment by deastr** [comment]
I'm having the same problem. Dungeon window was skinned when I was in my WoD garrison (I'm level 98) it was skinned but when I went into Legion Dalaran the window became unskinned.

**Comment by MisterT87** [comment]
@deastr: I cant agree with that I have the exact same problem in WoD Garnision as in new Dalaran...
in Both zones windows are not skinned.

Gethe: Got 2 Lua errors (tested with v8.0.1.1) after reload command:

Lua Error 1:
[https://pastebin.com/aZCg2FUP](https://pastebin.com/aZCg2FUP)

Lua Error 2:
[https://pastebin.com/RdXifmMt](https://pastebin.com/RdXifmMt)

**Comment by Gethe** [comment]
The first error was fixed in a recent push. It should be in the latest alpha version.

**Comment by MisterT87** [comment]
@Gethe @deastr  Can Agree: With 8.0.1.1-2-g21b392f release all is working again and LUA Error 1 is gone.

Really sure the second Lua Error isnt related to Aurora :)
