### ISSUE TITLE
Garrison/Class Hall UI

### ISSUE THREAD

**Issue by kgwium** [Haleth/Aurora#126]
Recently updated Aurora and this error pops up occasionally when I open up the garrison/class hall UI using the garrison/class hall report button next to the minimap.

------

2x ...ra\Skin\FrameXML\FloatingGarrisonFollowerTooltip.lua:37: attempt to index local 'Frame' (a nil value)
...ra\Skin\FrameXML\FloatingGarrisonFollowerTooltip.lua:37: in function `GarrisonFollowerTooltipContentsTemplate'
Aurora\Skin\FrameXML\GameTooltip.lua:92: in function `InternalEmbeddedItemTooltipTemplate'
...ceAurora\SkinBlizzard_GarrisonUI-1.0.lua:411: in function `addonModule'
Aurora\Skin\init.lua:137: in function <Aurora\Skin\init.lua:88>
[C]: ?
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:429: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:603: in function `OrderHall_LoadUI'
FrameXML\GarrisonBaseUtils.lua:210: in function `ShowGarrisonLandingPage'
FrameXML\Minimap.lua:600: in function `GarrisonLandingPage_Toggle'
FrameXML\Minimap.lua:593: in function <FrameXML\Minimap.lua:592>

Locals:
Frame = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'Frame' (a nil value)"
Skin = <table> {
 GarrisonFollowerTooltipTemplate = <function> defined @Aurora\Skin\FrameXML\FloatingGarrisonFollowerTooltip.lua:52
 AchievementHeaderStatusBarTemplate = <function> defined @Aurora\SkinBlizzard_AchievementUI.lua:240
 GossipFramePanelTemplate = <function> defined @Aurora\Skin\FrameXML\GossipFrame.lua:45
 UIPanelScrollUpButtonTemplate = <function> defined @Aurora\Skin\SharedXML\SecureUIPanelTemplates.lua:45
 PopupButtonTemplate = <function> defined @Aurora\Skin\FrameXML\ItemButtonTemplate.lua:109
 PetBattleUnitTooltipAuraTemplate = <function> defined @Aurora\SkinBlizzard_PetBattleUI.lua:131
 TooltipBorderedFrameTemplate = <function> defined @Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:342
 SplashFeatureFrameTemplate = <function> defined @Aurora\Skin\FrameXML\SplashFrame.lua:11
 ComparisonPlayerTemplate = <function> defined @Aurora\SkinBlizzard_AchievementUI.lua:314
 OptionsListButtonTemplate = <function> defined @Aurora\Skin\FrameXML\OptionsFrameTemplates.lua:42
 MoneyInputFrameTemplate = <function> defined @Aurora\Skin\FrameXML\MoneyInputFrame.lua:17
 HybridScrollBarTemplate = <function> defined @Aurora\Skin\SharedXML\HybridScrollFrame.lua:24
 ChannelButtonHeaderTemplate = <function> defined @Aurora\SkinBlizzard_Channels.lua:57
 InputBoxTemplate = <function> defined @Aurora\Skin\SharedXML\SecureUIPanelTemplates.lua:16
 ContainerFrameHelpBoxTemplate = <function> defined @Aurora\Skin\FrameXML\ContainerFrame.lua:120
 GarrisonLargeFollowerXPFrameTemplate = <function> defined @Aurora\SkinBlizzard_GarrisonUI.lua:249
 AchievementSearchPreviewButton = <function> defined @Aurora\SkinBlizzard_AchievementUI.lua:149
 BankItemButtonBagTemplate = <function> defined @Aurora\Skin\FrameXML\BankFrame.lua:48
 MaximizeMinimizeButtonFrameTemplate = <function> defined @Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:485
 UIPanelScrollDownButtonTemplate = <function> defined @Aurora\Skin\SharedXML\SecureUIPanelTemplates.lua:56
 CollectionsBackgroundTemplate = <function> defined @Aurora\SkinBlizzard_Collections.lua:119
 UICheckButtonTemplate = <function> defined @Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:226
 ChatConfigBoxTemplate = <function> defined @Aurora\Skin\FrameXML\ChatConfigFrame.lua:87
 GarrisonFollowerEquipmentTemplate = <function> defined @Aurora\SkinBlizzard_GarrisonTemplates.lua:234
 CollectionsProgressBarTemplate = <function> defined @Aurora\SkinBlizzard_Collections.lua:111
 PaperDollItemSlotButtonLeftTemplate = <function> defined @Aurora\Skin\FrameXML\PaperDollFrame.lua:69
 PortraitFrameTemplate = <function> defined @Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:298
 PetBattleActionButtonTemplate = <function> defined @Aurora\SkinBlizzard_PetBattleUI.lua:253
 WardrobeSetsTransmogModelTemplate = <function> defined @Aurora\SkinBlizzard_Collections.lua:178
 GarrisonFollowerCombatAllySpellTemplate = <function> defined @Aurora\SkinBlizzard_GarrisonTemplates.lua:231
 ChannelButtonCommunityTemplate = <function> defined @Aurora\SkinBlizzard_Channels.lua:92
 NavButtonPrevious = <function> defined @Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:79
 NavButtonTemplate = <function> defined @Aurora\Skin\FrameXML\NavigationBar.lua:28
 ChatConfigCheckButtonT

**Comment by Gethe** [comment]
This was fixed in commit 21b392feebe50c1738a31ba391737cab311f0318

Another release will be made later today.
