### ISSUE TITLE
Is Aurora supposed to remove the black background for quest objective list?

### ISSUE THREAD

**Issue by blakbyrd** [Haleth/Aurora#127]
### Prerequisites ###

* [x] Are you running the [latest release of Aurora](https://github.com/Haleth/Aurora/releases)? If you're using the Twitch updater, make sure the release type is set to "Release" unless told otherwise.
* [x] Did you [perform a cursory search](https://github.com/Haleth/Aurora/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?

### Description ###

It seems like this black background just appeared after updating Aurora.  I'm not sure if it was Aurora that got rid of it previously.

### Steps to Reproduce ###

1. Have Aurora active
2. [Second Step]
3. [Other Steps...]

**Expected behavior:**

No background

**Actual behavior:**

black background behind the word "Quests"

``` lua
-- If you recived an error, place it here.
```

``` lua
-- Separate them if you have more than one.
```

### Additional information ###

* Problem started happening recently, didn't happen in an older version of Aurora: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Screenshots and GIFs**

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)
![aurora quest](https://user-images.githubusercontent.com/40675374/42060324-49839ca6-7adb-11e8-89b3-cdbaa2be63cf.png)

**Installed AddOns:**

[List of installed addons which may conflict with the Aurora skin]

**Comment by Gethe** [comment]
No, that background is actually the replacement for the original. The background is there to ensure the text is readable in a variety of environments.

**Comment by blakbyrd** [comment]
Gotcha.  I found the BLP for it and made it blank.  

Here's something to think about from a design standpoint:  That seems to be the only part of the quest log with a background.  For me, that would be the least important part of the quest log to have a background.  It's the quest names and objectives that I need to be able to read (which do not have a background).  

Thanks for getting back to me so quickly, Gethe!
