### ISSUE TITLE
Check-marks of checked Check-boxes are misaligned

### ISSUE THREAD

**Issue by flowild** [Haleth/Aurora#129]
### Prerequisites ###

Using the Twitch updater. Aurora 8.0.1.3 for game version 7.3.5. Twitch updater is set to "release".
Disabled all other addons. Tried reinstalling.

### Description ###

Check-marks of checked Check-boxes are misaligned on the world map. 

Without any other addons:
https://i.imgur.com/PlFbv1I.jpg

With full UI and "World Quest List" and "Mapster":
https://i.imgur.com/WFgrLY8.jpg

### Steps to Reproduce ###

1. Open World map
2. click magnifying glass in the top right

### Additional information ###

* Problem started happening recently, didn't happen in an older version of Aurora: [Don't know]

* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Installed AddOns:**

The alt i took the first screenshot on above has no other addons enabled. After i disabled all addons i reinstalled aurora. Same problem. 
But if it helps here are the addons in normally use:
[addons.txt](https://github.com/Haleth/Aurora/files/2195498/addons.txt)

**Comment by Gethe** [comment]
fixed in 9bbcdcfddf4c83d909c3333379ac3b35cd4b6fc7
