### ISSUE TITLE
Tooltips with Blue Background

### ISSUE THREAD

**Issue by agentschmitt** [Haleth/Aurora#134]
### Prerequisites ###

* [x] Are you running the [latest release of Aurora](https://github.com/Haleth/Aurora/releases)? Yes 8.0.1.6
* [x] Did you [perform a cursory search](https://github.com/Haleth/Aurora/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?
Yes found a similar one but closed. https://github.com/Haleth/Aurora/issues/120

### Description ###
I get blue background tooltips on all my databrokers and on the wow standard tooltip.

### Steps to Reproduce ###

1. Mouseover something
2.Tooltip with blue background occurs
3. Move Mouse away and back
4. Tooltip gets transparent again

**Expected behavior:**

Tooltip should get transparent instead of blue.

### Additional information ###

**Screenshots and GIFs**

https://imgur.com/a/Ypa7Wjl

**Installed AddOns:**

[List of installed addons which may conflict with the Aurora skin]
!BugGrabber
AdiBags
AdiBags_Config
AdiBags_Hearthstones
AdvancedInterfaceOptions
Ara_Broker_Guild_Friends
Auctionator
Aurora
AverageItemLevel
AzeriteTooltip
Azeroth Auto Pilot
BagSync
Bartender4
BetterBlizzOptions
BigWigs
BigWigs_Core
BigWigs_Options
BigWigs_Plugins
BigWigs_Uldir
BigWigs_Voice
BlizzMove
BrokerDualSpec
Broker_BagFu
Broker_Currencyflow
Broker_DurabilityInfo
Broker_ProfessionsMenu
broker_simulationcraft
Broker_uClock
BtWQuests
BtWQuestsBattleForAzeroth
BugSack
BuyEmAll
ChampionCommander
ChocolateBar
Clique
Details
Details_3DModelsPaths
Details_DataStorage
Details_DmgRank
Details_DpsTuning
Details_EncounterDetails
Details_RaidCheck
Details_Streamer
Details_TimeAttack
Details_TinyThreat
Details_Vanguard
ErrorFilter
ExRT
ExtraQuestButton
Gallywix_Azerite_Ledger
GatherMate2
Gnosis
Grid2
Grid2LDB
Grid2Options
Grid2RaidDebuffs
Grid2RaidDebuffsOptions
GTFO
Kib_QuestMobs
Kui_Media
Kui_Nameplates
Kui_Nameplates_Core
Kui_Nameplates_Core_Config
Kui_SpellList_Config
Leatrix_Plus
LegionInvasionTimer
LegionInvasionTimer_Options
LittleWigs
MapCoords
Masque
Masque_CleanUI
Masque_Renaitre
MoveAnything
OmniCC
OmniCC_Config
PhanxChat
RaiderIO
RaiderIO_DB_EU_A
RaiderIO_DB_EU_H
RaiderIO_DB_KR_A
RaiderIO_DB_KR_H
RaiderIO_DB_TW_A
RaiderIO_DB_TW_H
RaiderIO_DB_US_A
RaiderIO_DB_US_H
RealmHopAssist
SavedInstances
SellJunk
SexyMap
ShadowedUF_Options
ShadowedUnitFrames
Simulationcraft
Skinner
StatBlock_Coords
StatBlock_FPS
StatBlock_Latency
StatBlock_Memory
StatBlock_TimeInFight
StatBlock_XP
StatBlock_ZoneText
WeakAuras
WeakAurasModelPaths
WeakAurasOptions
WeakAurasTemplates
WIM
WIM_FlatPanel
WorldQuestTracker

**Comment by Gethe** [comment]
I would bet this is due to Skinner. I recommend using only one of either Aurora or Skinner.

**Comment by agentschmitt** [comment]
Ah sorry Skinner is disabled. I used it before Aurora. But like the Layout of Aurora more :)

**Comment by agentschmitt** [comment]
Ok i found the conflicting addon. It was Leatrix Plus.
I had enabled Tooltip color based on faction....
Didn't think it colors also Tooltips of Broker Addons :-P
