### ISSUE TITLE
Tooltip border.

### ISSUE THREAD

**Issue by kgwium** [Haleth/Aurora#141]
After the latest update, this is the issue I am getting.

No error pops up,  just this white border around the tooltip when I hover over items, that whitebox wasn´t there yesterday. 
I have been going through the settings and I can´t seem to find how to fix it myself.

![White Box](https://i.imgur.com/d5MVyWE.jpg)

And on some items,  the border won´t show on all the sides of the tooltip like this here.

![White Box](https://i.imgur.com/mc9wsdT.jpg)

**Comment by Gethe** [comment]
I'm not seeing this issue. Try disabling all except Aurora, there may be a conflict.

**Comment by kgwium** [comment]
It could be some conflict between Tipbuddy and Aurora.
I logged onto one of my alts and disabled every addon except Aurora,  no border,  then I enabled addons one by one and came to Tipbuddy which gave me this border,  I was able to disable it on my alt and immediately logged onto my main and was not able to replicate the change and the white border is still around the icons.
