### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by RodesDKeu** [Haleth/Aurora#146]
### Prerequisites ###

* [x] Are you running the [latest release of Aurora](https://github.com/Haleth/Aurora/releases)? If you're using the Twitch updater, make sure the release type is set to "Release" unless told otherwise.
* [ ] Did you [perform a cursory search](https://github.com/Haleth/Aurora/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?

### Description ###

[Short description of problem here]

### Steps to Reproduce ###

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**Expected behavior:**

[Describe expected behavior here]

LUA ERROR SCREEN:

Message: ...nterface\AddOns\Aurora\Skin\FrameXML\SplashFrame.lua:36: Usage: GetAtlasInfo("atlasName")
Time: Mon Nov 26 03:29:45 2018
Count: 1
Stack: ...nterface\AddOns\Aurora\Skin\FrameXML\SplashFrame.lua:36: Usage: GetAtlasInfo("atlasName")
[C]: in function `GetAtlasInfo'
...nterface\AddOns\Aurora\Skin\FrameXML\SplashFrame.lua:36: in function `?'
Interface\AddOns\Aurora\Skin\init.lua:119: in function <Interface\AddOns\Aurora\Skin\init.lua:91>

Locals: (*temporary) = nil

[Describe observed behavior here]

``` lua
-- If you recived an error, place it here.
```

``` lua
-- Separate them if you have more than one.
```

### Additional information ###

* Problem started happening recently, didn't happen in an older version of Aurora: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]

**Screenshots and GIFs**

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

**Installed AddOns:**

[List of installed addons which may conflict with the Aurora skin]

**Comment by Mindlessgalaxy** [comment]
Hi,

Just thought I would let you know I am having exactly the same issue as well.  I have deleted the addon and reinstalled it from scratch as well with no remedy at all.  English US, Oceanic both Horde and Alliance Toons all from level 27 through to 118 and all classes as well as most races.

Thanks for an awesome addon as well, love this one :)

Thanks in advance.

Mindlessgalaxy.

PS:  Only been playing up with the new update and previous release is working fine as far as I can tell anyway.

**Comment by Gethe** [comment]
I haven't encountered this error at all. Have you tried with just Aurora enabled?

**Comment by RacerDemon** [comment]
Same issue
