### ISSUE TITLE
Several errors after installing latest version 8.0.19

### ISSUE THREAD

**Issue by wowcamo** [Haleth/Aurora#147]
error 1:

1x ...eAurora\SkinBlizzard_Collections-1.0.lua:61: attempt to index field '_auroraIconBorder' (a nil value)
...eAurora\SkinBlizzard_Collections-1.0.lua:61: in function <...eAurora\SkinBlizzard_Collections.lua:48>
[C]: in function `PetJournal_UpdatePetList'
...dOns\Blizzard_Collections\Blizzard_PetCollection.lua:163: in function <...dOns\Blizzard_Collections\Blizzard_PetCollection.lua:141>

Locals:
scrollFrame = PetJournalListScrollFrame {
 0 = <userdata>
 buttons = <table> {
 }
 ScrollChild = PetJournalListScrollFrameScrollChild {
 }
 scrollUp = PetJournalListScrollFrameScrollBarScrollUpButton {
 }
 totalHeight = 69322
 range = 68867
 scrollDown = PetJournalListScrollFrameScrollBarScrollDownButton {
 }
 offset = 0
 scrollBar = PetJournalListScrollFrameScrollBar {
 }
 buttonHeight = 46
 update = <function> defined =[C]:-1
 scrollChild = PetJournalListScrollFrameScrollChild {
 }
}
offset = 0
petButtons = <table> {
 1 = PetJournalListScrollFrameButton1 {
 }
 2 = PetJournalListScrollFrameButton2 {
 }
 3 = PetJournalListScrollFrameButton3 {
 }
 4 = PetJournalListScrollFrameButton4 {
 }
 5 = PetJournalListScrollFrameButton5 {
 }
 6 = PetJournalListScrollFrameButton6 {
 }
 7 = PetJournalListScrollFrameButton7 {
 }
 8 = PetJournalListScrollFrameButton8 {
 }
 9 = PetJournalListScrollFrameButton9 {
 }
 10 = PetJournalListScrollFrameButton10 {
 }
 11 = PetJournalListScrollFrameButton11 {
 }
 12 = PetJournalListScrollFrameButton12 {
 }
}
numPets = 1507
(for index) = 1
(for limit) = 12
(for step) = 1
i = 1
pet = PetJournalListScrollFrameButton1 {
 0 = <userdata>
 petTypeIcon = PetJournalListScrollFrameButton1PetTypeIcon {
 }
 dragButton = <unnamed> {
 }
 owned = true
 subName = PetJournalListScrollFrameButton1SubName {
 }
 newGlow = <unnamed> {
 }
 isDead = <unnamed> {
 }
 index = 1
 petID = "BattlePet-0-0000047E9ACF"
 selectedTexture = <unnamed> {
 }
 name = PetJournalListScrollFrameButton1Name {
 }
 iconBorder = PetJournalListScrollFrameButton1IconBorder {
 }
 speciesID = 1624
 selected = false
 icon = PetJournalListScrollFrameButton1Icon {
 }
 new = <unnamed> {
 }
}
index = 1
_ = 1400
_ = 1400
_ = 325
_ = 260
rarity = 4
color = <table> {
 hex = "|cff0070dd"
 r = 0
 color = <table> {
 }
 g = 0.43921568627451
 b = 0.86666666666667
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '_auroraIconBorder' (a nil value)"
Color = <table> {
 highlight = <table> {
 }
 cyan = <table> {
 }
 Lightness = <function> defined @Aurora\Skin\api.lua:832
 grayLight = <table> {
 }
 Saturation = <function> defined @Aurora\Skin\api.lua:824
 button = <table> {
 }
 red = <table> {
 }
 Hue = <function> defined @Aurora\Skin\api.lua:809
 blue = <table> {
 }
 Post = <table> {
 }
 Create = <function> defined @Aurora\Skin\api.lua:852
 white = <table> {
 }
 frame = <table> {
 }
 grayDark = <table> {
 }
 black = <table> {
 }
 green = <table> {
 }
 Pre = <table> {
 }
 yellow = <table> {
 }
 violet = <table> {
 }
 gray = <table> {
 }
}

error 2:

17x Aurora\Skin\init.lua:141: attempt to index field 'themes' (a nil value)
Aurora\Skin\init.lua:141: in function <Aurora\Skin\init.lua:91>

Locals:
self = <unnamed> {
 0 = <userdata>
}
event = "ADDON_LOADED"
addonName = "AutoAcceptEnchantReplace"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'themes' (a nil value)"
private = <table> {
 isPatch = false
 disabled = <table> {
 }
 uiScale = 1
 API_MINOR = 3
 SetupGUI = <function> defined @Aurora\gui.lua:375
 API_MAJOR = 0
 classColorsHaveChanged = <function> defined @Aurora\aurora.lua:95
 TRIVIAL_QUEST_DISPLAY = "|cffbfbfbf%s (low level)|r"
 updateHighlightColor = <function> defined @Aurora\aurora.lua:84
 Aurora = <table> {
 }
 debug = <function> defined @Aurora\Skin\init.lua:53
 charClass = <table> {
 }
 FRAME_TITLE_HEIGHT = 27
 backdrop = <table> {
 }
 FrameXML = <table> {
 }
 OnLoad = <function> defined @Aurora\aurora.lua:38
 font = <table> {
 }
 AddOns = <table> {
 }
 NORMAL_QUEST_DISPLAY = "|cffffffff%s|r"
 classColorsInit = <function> defined @Aurora\aurora.lua:110
 SharedXML = <table> {
 }
 nop = <function> defined @Aurora\Skin\init.lua:47
 UpdateUIScale = <function> defined @Aurora\Skin\api.lua:583
}
ADDON_NAME = "Aurora"
Aurora = <table> {
 highlightColor = <table> {
 }
 Hook = <table> {
 }
 1 = <table> {
 }
 Color = <table> {
 }
 buttonColor = <table> {
 }
 2 = <table> {
 }
 frameColor = <table> {
 }
 Skin = <table> {
 }
 classIcons = <table> {
 }
 Scale = <table> {
 }
 Base = <table> {
 }
 Util = <table> {
 }
}

error 3:

1x ...rfaceClassic Quest Log\Classic Quest Log-1.4.1.lua:902: attempt to call field 'ReskinPortraitFrame' (a nil value)
...rfaceClassic Quest Log\Classic Quest Log-1.4.1.lua:902: in function `SkinForAurora'
...rfaceClassic Quest Log\Classic Quest Log-1.4.1.lua:36: in function `OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
self = ClassicQuestLog {
 0 = <userdata>
 close = <unnamed> {
 }
 SelectQuestIndex = <function> defined @Classic Quest Log\Classic Quest Log.lua:519
 portraitIcon = <unnamed> {
 }
 UpdateLogList = <function> defined @Classic Quest Log\Classic Quest Log.lua:150
 Inset = ClassicQuestLogInset {
 }
 emptyLog = <unnamed> {
 }
 OnShow = <function> defined @Classic Quest Log\Classic Quest Log.lua:76
 TitleBg = ClassicQuestLogTitleBg {
 }
 HandleObjectiveTracker = <function> defined @Classic Quest Log\Classic Quest Log.lua:761
 BotRightCorner = ClassicQuestLogBotRightCorner {
 }
 count = <unnamed> {
 }
 RecurseRecolor = <function> defined @Classic Quest Log\Classic Quest Log.lua:849
 RightBorder = ClassicQuestLogRightBorder {
 }
 UpdateLog = <function> defined @Classic Quest Log\Classic Quest Log.lua:155
 TopRightCorner = ClassicQuestLogTopRightCorner {
 }
 Bg = ClassicQuestLogBg {
 }
 OnLoad = <function> defined @SharedXML\SharedUIPanelTemplates.lua:860
 mapButton = <unnamed> {
 }
 ListEntryOnClick = <function> defined @Classic Quest Log\Classic Quest Log.lua:382
 push = <unnamed> {
 }
 overridingKey = "L"
 OnSizeChanged = <function> defined @Classic Quest Log\Classic Quest Log.lua:66
 TitleText = ClassicQuestLogTitleText {
 }
 portrait = ClassicQuestLogPortrait {
 }
 update = <unnamed> {
 }
 UpdateControlButtons = <function> defined @Classic Quest Log\Classic Quest Log.lua:543
 ShowMap = <function> defined @Classic Quest Log\Classic Quest Log.lua:573
 TopLeftCorner = ClassicQuestLogTopLeftCorner {
 }
 optionsFrame = <unnamed> {
 }
 UpdateQuestDetail = <function> defined @Classic Quest Log\Classic Quest Log.lua:348
 options = <unnamed> {
 }
 RecoloredFontStrings = <table> {
 }
 UpdateOverrides = <function> defined @Classic Quest Log\Classic Quest Log.lua:593
 UpdateDocking = <function> defined @Classic Quest Log\Classic Quest Log.lua:727
 ToggleWindow = <function> defined @Classic Quest Log\Classic Quest Log.lua:621
 abandon = <unnamed> {
 }
 oldToggleQuestLog = <function> defined @Blizzard_WorldMap\Blizzard_WorldMap.lua:400
 SkinForAurora = <function> defined @Classic Quest Log\Classic Quest Log.lua:893
 OptionOnEnter = <function> defined @Classic Quest Log\Classic Quest Log.lua:682
 resizeGrip = <unnamed> {
 }
 PortraitFrame = ClassicQuestLogPortraitFrame {
 }
 LeftBorder = ClassicQuestLogLeftBorder {
 }
 RecolorDetailText = <function> defined @Classic Quest Log\Classic Quest Log.lua:834
 RecolorObjectivesText = <function> defined @Classic Quest Log\Classic Quest Log.lua:816
 track = <unnamed> {
 }
 ToggleWatch = <function> defined @Classic Quest Log\Classic Quest Log.lua:401
 UpdateDetailColors = <function> defined @Classic Quest Log\Classic Quest Log.lua:789
 ShowWindow = <function> defined @Classic Quest Log\Classic Quest Log.lua:633
 ListEntryOnEnter = <function> defined @Classic Quest Log\Classic Quest Log.lua:419
 UpdateOptionsForSkins = <function> defined @Classic Quest Log\Classic Quest Log.lua:752
 ExpandAllOnClick = <function> defined @Classic Quest Log\Classic Quest Log.lua:557
 UpdateBackgrounds = <function> defined @Classic Quest Log\Classic Quest Log.lua:737
 SealMaterialBG = <unnamed> {
 }
 scrollFrame = ClassicQuestLogScrollFrame {
 }
 HideWindow = <function> defined @Classic Quest Log\Classic Quest Log.lua:625
 OptionsUpdate = <function> defined @Classic Quest Log\Classic Quest Log.lua:712
 TopBorder = ClassicQuestLogTopBorder {
 }
 TopTileStreaks = ClassicQuestLogTopTileStreaks {
 }
 OnHide = <function> defined @Classic Quest Log\Classic Quest Log.lua:113
 BottomBorder = ClassicQuestLogBottomBorder {
 }
 OptionOnC

error 4:

1x Aurora\aurora-8.0.1.9.lua:102: attempt to call method 'IsEqualTo' (a nil value)
Aurora\aurora-8.0.1.9.lua:102: in function `classColorsHaveChanged'
Aurora\aurora-8.0.1.9.lua:111: in function `classColorsInit'
Aurora\Skin\SharedXML\Util.lua:37: in function `?'
Aurora\Skin\init.lua:119: in function <Aurora\Skin\init.lua:91>

Locals:
hasChanged = false
(for index) = 1
(for limit) = 12
(for step) = 1
i = 1
classToken = "WARRIOR"
color = <table> {
 b = 0.43
 colorStr = "ffc69b6d"
 g = 0.61
 r = 0.78
}
cache = <table> {
 r = 0.78
 colorStr = "ffc79c6e"
 g = 0.61
 b = 0.43
}
(*temporary) = nil
(*temporary) = <table> {
 b = 0.43
 colorStr = "ffc69b6d"
 g = 0.61
 r = 0.78
}
(*temporary) = <table> {
 r = 0.78
 colorStr = "ffc79c6e"
 g = 0.61
 b = 0.43
}
(*temporary) = "attempt to call method 'IsEqualTo' (a nil value)"
customClassColors = <table> {
 HUNTER = <table> {
 }
 WARRIOR = <table> {
 }
 ROGUE = <table> {
 }
 MAGE = <table> {
 }
 PRIEST = <table> {
 }
 SHAMAN = <table> {
 }
 WARLOCK = <table> {
 }
 DEMONHUNTER = <table> {
 }
 DEATHKNIGHT = <table> {
 }
 DRUID = <table> {
 }
 MONK = <table> {
 }
 PALADIN = <table> {
 }
}

error 5:

1x Aurora\Skin\deprecated.lua:57: attempt to call method 'GetRGB' (a nil value)
Aurora\Skin\deprecated.lua:57: in main chunk

Locals:
ADDON_NAME = "Aurora"
private = <table> {
 isPatch = false
 API_MAJOR = 0
 nop = <function> defined @Aurora\Skin\init.lua:47
 charClass = <table> {
 }
 API_MINOR = 3
 CreateAPI = <function> defined @Aurora\Skin\deprecated.lua:13
 backdrop = <table> {
 }
 font = <table> {
 }
 UpdateUIScale = <function> defined @Aurora\Skin\api.lua:583
 Aurora = <table> {
 }
 debug = <function> defined @Aurora\Skin\init.lua:53
 disabled = <table> {
 }
 uiScale = 1
}
Aurora = <table> {
 highlightColor = <table> {
 }
 Hook = <table> {
 }
 1 = <table> {
 }
 Color = <table> {
 }
 buttonColor = <table> {
 }
 2 = <table> {
 }
 frameColor = <table> {
 }
 Skin = <table> {
 }
 classIcons = <table> {
 }
 Scale = <table> {
 }
 Base = <table> {
 }
 Util = <table> {
 }
}
Base = <table> {
 SetHighlight = <function> defined @Aurora\Skin\api.lua:397
 GetSkinList = <function> defined @Aurora\Skin\api.lua:41
 SetTexture = <function> defined @Aurora\Skin\api.lua:530
 CreateBackdrop = <function> defined @Aurora\Skin\api.lua:301
 SetBackdrop = <function> defined @Aurora\Skin\deprecated.lua:28
 CreateColor = <function> defined @Aurora\Skin\api.lua:852
 Post = <table> {
 }
 IsTextureRegistered = <function> defined @Aurora\Skin\api.lua:526
 RegisterTexture = <function> defined @Aurora\Skin\api.lua:548
 CropIcon = <function> defined @Aurora\Skin\api.lua:55
 Pre = <table> {
 }
 AddSkin = <function> defined @Aurora\Skin\api.lua:33
 SetFont = <function> defined @Aurora\Skin\api.lua:329
 SetBackdropColor = <function> defined @Aurora\Skin\deprecated.lua:38
}
Skin = <table> {
 Pre = <table> {
 }
 Post = <table> {
 }
}
Color = <table> {
 highlight = <table> {
 }
 cyan = <table> {
 }
 Lightness = <function> defined @Aurora\Skin\api.lua:832
 grayLight = <table> {
 }
 Saturation = <function> defined @Aurora\Skin\api.lua:824
 button = <table> {
 }
 red = <table> {
 }
 Hue = <function> defined @Aurora\Skin\api.lua:809
 blue = <table> {
 }
 Post = <table> {
 }
 Create = <function> defined @Aurora\Skin\api.lua:852
 white = <table> {
 }
 frame = <table> {
 }
 grayDark = <table> {
 }
 black = <table> {
 }
 green = <table> {
 }
 Pre = <table> {
 }
 yellow = <table> {
 }
 violet = <table> {
 }
 gray = <table> {
 }
}
newSetBackdrop = <function> defined @Aurora\Skin\api.lua:315
newSetBackdropColor = <function> defined @Aurora\Skin\api.lua:319
F = <table> {
}
C = <table> {
}
(*temporary) = nil
(*temporary) = <table> {
 b = 0.43
 colorStr = "ffc69b6d"
 g = 0.61
 r = 0.78
}
(*temporary) = "attempt to call method 'GetRGB' (a nil value)"

All errors occur during log on, if you need other info let me know.

**Comment by Gethe** [comment]
Do you still get these errors with just Aurora enabled?

**Comment by wowcamo** [comment]
Sorry about the time between responses, went out of town and couldn't troubleshoot it.  In any case the errors don't show themselves when Aurora is loaded by itself...  The culprit seems to be the addon Class Color located here: [(https://www.curseforge.com/wow/addons/classcolors](url)).  It's been updated on July so it's fairly recent.

**Comment by Gethe** [comment]
Aurora implements ClassColors on its own, so you don't need both.

**Comment by wowcamo** [comment]
That's great, one less addon to keep track of.
