### ISSUE TITLE
8.1 Errors?

### ISSUE THREAD

**Issue by Justw8** [Haleth/Aurora#148]
8x Aurora\Skin\api.lua:535: arrowUp is not a registered texture.
[C]: in function `assert'
Aurora\Skin\api.lua:535: in function `SetTexture'
...Ons\Aurora\Skin\SharedXML\SecureUIPanelTemplates.lua:52: in function `UIPanelScrollUpButtonTemplate'
...eAurora\Skin\SharedXML\HybridScrollFrame.lua:45: in function `HybridScrollBarTemplate'
Aurora\SkinBlizzard_AchievementUI-1.0.lua:442: in function `addonModule'
Aurora\Skin\init.lua:136: in function <Aurora\Skin\init.lua:91>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:449: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:564: in function `AchievementFrame_LoadUI'
FrameXML\AlertFrames.lua:454: in function <FrameXML\AlertFrames.lua:445>

32x Aurora\Skin\api.lua:535: gradientUp is not a registered texture.
[C]: in function `assert'
Aurora\Skin\api.lua:535: in function `SetTexture'
Aurora\aurora-8.0.1.9.lua:146: in function <Aurora\aurora.lua:143>
[C]: in function `SetBackdrop'
...Ons\Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:207: in function `UIPanelCloseButton'
...Ons\Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:374: in function `PortraitFrameTemplate'
...Ons\Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:378: in function `ButtonFrameTemplate'
...s\Aurora\SkinBlizzard_ScrappingMachineUI.lua:45: in function `addonModule'
Aurora\Skin\init.lua:136: in function <Aurora\Skin\init.lua:91>
[C]: in function `LoadAddOn'
EasyScrap\EasyScrap-18.lua:2: in main chunk

1x ...eAurora\SkinBlizzard_Communities.lua:45: attempt to index field '_iconBorder' (a nil value)
...eAurora\SkinBlizzard_Communities.lua:45: in function <...eAurora\SkinBlizzard_Communities.lua:41>
[C]: in function `SetAddCommunity'
...faceBlizzard_Communities\CommunitiesList.lua:249: in function `Update'
...faceBlizzard_Communities\CommunitiesList.lua:321: in function <...faceBlizzard_Communities\CommunitiesList.lua:316>
[C]: in function `Show'
FrameXML\UIParent.lua:2635: in function `SetUIPanel'
FrameXML\UIParent.lua:2480: in function `ShowUIPanel'
FrameXML\UIParent.lua:2348: in function <FrameXML\UIParent.lua:2344>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:3176: in function `ShowUIPanel'
FrameXML\UIParent.lua:3160: in function `ToggleFrame'
FrameXML\UIParent.lua:930: in function `ToggleCommunitiesFrame'
FrameXML\UIParent.lua:816: in function `ToggleGuildFrame'
[string "TOGGLEGUILDTAB"]:1: in function <[string "TOGGLEGUILDTAB"]:1>

Locals:
self = CommunitiesFrameCommunitiesListListScrollFrameButton5 {
 0 = <userdata>
 OnEnter = <function> defined @Blizzard_Communities\CommunitiesList.lua:627
 IsTicket = <function> defined @Blizzard_Communities\CommunitiesList.lua:596
 GetCommunitiesList = <function> defined @Blizzard_Communities\CommunitiesList.lua:600
 Icon = <unnamed> {
 }
 CircleMask = <unnamed> {
 }
 Selection = <unnamed> {
 }
 SetAddCommunity = <function> defined =[C]:-1
 UnreadNotificationIcon = <unnamed> {
 }
 Background = <unnamed> {
 }
 SetClubInfo = <function> defined =[C]:-1
 OnClick = <function> defined @Blizzard_Communities\CommunitiesList.lua:635
 InvitationIcon = <unnamed> {
 }
 GetClubId = <function> defined @Blizzard_Communities\CommunitiesList.lua:588
 GetCommunitiesFrame = <function> defined @Blizzard_Communities\CommunitiesList.lua:604
 OnShow = <function> defined @Blizzard_Communities\CommunitiesList.lua:608
 GuildTabardBorder = <unnamed> {
 }
 OnHide = <function> defined @Blizzard_Communities\CommunitiesList.lua:612
 GuildTabardEmblem = <unnamed> {
 }
 SetFocused = <function> defined @Blizzard_Communities\CommunitiesList.lua:582
 OnEvent = <function> defined @Blizzard_Communities\CommunitiesList.lua:616
 SetGuildFinder = <function> defined @Blizzard_Communities\CommunitiesList.lua:543
 FavoriteIcon = <unnamed> {
 }
 Name = <unnamed> {
 }
 GuildTabardBackground = <unnamed> {
 }
 UpdateUnreadNotification = <function> defined @Blizzard_Communities\CommunitiesList.lua:500
 IconRing = <unnamed> {
 }
 overrideOnClick = <function> defined @Blizzard_Communities\CommunitiesList.lua:507
 IsInvitation = <function> defined @Blizzard_Communities\CommunitiesList.lua:592
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "CENTER"
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = 10
(*temporary) = 0
(*temporary) = "attempt to index field '_iconBorder' (a nil value)"
Color = <table> {
 highlight = <table> {
 }
 cyan = <table> {
 }
 Lightness = <function> defined @Aurora\Skin\api.lua:832
 grayLight = <table> {
 }
 Saturation = <function> defined @Aurora\Skin\api.lua:824
 button = <table> {
 }
 red = <table> {
 }
 Hue = <function> defined @Aurora\Skin\api.lua:809
 blue = <table> {
 }
 Post = <table> {
 }
 Create = <function> defined @Aurora\Skin\api.lua:852
 white = <table> {
 }
 frame = <table> {
 }
 grayDark = <table> {
 }
 black = <table> {
 }
 green = <table> {
 }
 Pre = <table> {
 }
 yellow = <table> {
 }
 violet = <table> {
 }
 gray = <table> {
 }
}

2x ...eAurora\SkinBlizzard_Communities.lua:31: attempt to index field '_iconBorder' (a nil value)
...eAurora\SkinBlizzard_Communities.lua:31: in function <...eAurora\SkinBlizzard_Communities.lua:16>
[C]: in function `SetClubInfo'
...faceBlizzard_Communities\CommunitiesList.lua:244: in function `Update'
...faceBlizzard_Communities\CommunitiesList.lua:321: in function <...faceBlizzard_Communities\CommunitiesList.lua:316>
[C]: in function `Show'
FrameXML\UIParent.lua:2635: in function `SetUIPanel'
FrameXML\UIParent.lua:2480: in function `ShowUIPanel'
FrameXML\UIParent.lua:2348: in function <FrameXML\UIParent.lua:2344>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:3176: in function `ShowUIPanel'
FrameXML\UIParent.lua:3160: in function `ToggleFrame'
FrameXML\UIParent.lua:930: in function `ToggleCommunitiesFrame'
FrameXML\UIParent.lua:816: in function `ToggleGuildFrame'
[string "TOGGLEGUILDTAB"]:1: in function <[string "TOGGLEGUILDTAB"]:1>

Locals:
self = CommunitiesFrameCommunitiesListListScrollFrameButton3 {
 0 = <userdata>
 OnEnter = <function> defined @Blizzard_Communities\CommunitiesList.lua:627
 IsTicket = <function> defined @Blizzard_Communities\CommunitiesList.lua:596
 isTicket = false
 isInvitation = false
 clubId = 119890422
 GetCommunitiesList = <function> defined @Blizzard_Communities\CommunitiesList.lua:600
 Icon = <unnamed> {
 }
 CircleMask = <unnamed> {
 }
 Selection = <unnamed> {
 }
 SetAddCommunity = <function> defined =[C]:-1
 UnreadNotificationIcon = <unnamed> {
 }
 Background = <unnamed> {
 }
 SetClubInfo = <function> defined =[C]:-1
 OnClick = <function> defined @Blizzard_Communities\CommunitiesList.lua:635
 InvitationIcon = <unnamed> {
 }
 GetClubId = <function> defined @Blizzard_Communities\CommunitiesList.lua:588
 GetCommunitiesFrame = <function> defined @Blizzard_Communities\CommunitiesList.lua:604
 OnShow = <function> defined @Blizzard_Communities\CommunitiesList.lua:608
 GuildTabardBorder = <unnamed> {
 }
 OnHide = <function> defined @Blizzard_Communities\CommunitiesList.lua:612
 GuildTabardEmblem = <unnamed> {
 }
 SetFocused = <function> defined @Blizzard_Communities\CommunitiesList.lua:582
 OnEvent = <function> defined @Blizzard_Communities\CommunitiesList.lua:616
 SetGuildFinder = <function> defined @Blizzard_Communities\CommunitiesList.lua:543
 FavoriteIcon = <unnamed> {
 }
 Name = <unnamed> {
 }
 GuildTabardBackground = <unnamed> {
 }
 UpdateUnreadNotification = <function> defined @Blizzard_Communities\CommunitiesList.lua:500
 IconRing = <unnamed> {
 }
 IsInvitation = <function> defined @Blizzard_Communities\CommunitiesList.lua:592
}
clubInfo = <table> {
 broadcast = ""
 description = "Hots"
 avatarId = 1
 clubType = 0
 joinTime = 1537815441000000
 clubId = 119890422
 name = "Hots"
 socialQueueingEnabled = false
}
isInvitation = false
isTicket = false
isGuild = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = "CENTER"
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = 10
(*temporary) = 0
(*temporary) = "attempt to index field '_iconBorder' (a nil value)"
Color = <table> {
 highlight = <table> {
 }
 cyan = <table> {
 }
 Lightness = <function> defined @Aurora\Skin\api.lua:832
 grayLight = <table> {
 }
 Saturation = <function> defined @Aurora\Skin\api.lua:824
 button = <table> {
 }
 red = <table> {
 }
 Hue = <function> defined @Aurora\Skin\api.lua:809
 blue = <table> {
 }
 Post = <table> {
 }
 Create = <function> defined @Aurora\Skin\api.lua:852
 white = <table> {
 }
 frame = <table> {
 }
 grayDark = <table> {
 }
 black = <table> {
 }
 green = <table> {
 }
 Pre = <table> {
 }
 yellow = <table> {
 }
 violet = <table> {
 }
 gray = <table> {
 }
}

1x ...eAurora\SkinBlizzard_Communities.lua:37: attempt to index field '_iconBorder' (a nil value)
...eAurora\SkinBlizzard_Communities.lua:37: in function <...eAurora\SkinBlizzard_Communities.lua:16>
[C]: in function `SetClubInfo'
...faceBlizzard_Communities\CommunitiesList.lua:244: in function `Update'
...faceBlizzard_Communities\CommunitiesList.lua:321: in function <...faceBlizzard_Communities\CommunitiesList.lua:316>
[C]: in function `Show'
FrameXML\UIParent.lua:2635: in function `SetUIPanel'
FrameXML\UIParent.lua:2480: in function `ShowUIPanel'
FrameXML\UIParent.lua:2348: in function <FrameXML\UIParent.lua:2344>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:3176: in function `ShowUIPanel'
FrameXML\UIParent.lua:3160: in function `ToggleFrame'
FrameXML\UIParent.lua:930: in function `ToggleCommunitiesFrame'
FrameXML\UIParent.lua:816: in function `ToggleGuildFrame'
[string "TOGGLEGUILDTAB"]:1: in function <[string "TOGGLEGUILDTAB"]:1>

Locals:
self = CommunitiesFrameCommunitiesListListScrollFrameButton2 {
 0 = <userdata>
 OnEnter = <function> defined @Blizzard_Communities\CommunitiesList.lua:627
 IsTicket = <function> defined @Blizzard_Communities\CommunitiesList.lua:596
 isTicket = false
 isInvitation = false
 clubId = 2592632
 GetCommunitiesList = <function> defined @Blizzard_Communities\CommunitiesList.lua:600
 Icon = <unnamed> {
 }
 CircleMask = <unnamed> {
 }
 Selection = <unnamed> {
 }
 SetAddCommunity = <function> defined =[C]:-1
 UnreadNotificationIcon = <unnamed> {
 }
 Background = <unnamed> {
 }
 SetClubInfo = <function> defined =[C]:-1
 OnClick = <function> defined @Blizzard_Communities\CommunitiesList.lua:635
 InvitationIcon = <unnamed> {
 }
 GetClubId = <function> defined @Blizzard_Communities\CommunitiesList.lua:588
 GetCommunitiesFrame = <function> defined @Blizzard_Communities\CommunitiesList.lua:604
 OnShow = <function> defined @Blizzard_Communities\CommunitiesList.lua:608
 GuildTabardBorder = <unnamed> {
 }
 OnHide = <function> defined @Blizzard_Communities\CommunitiesList.lua:612
 GuildTabardEmblem = <unnamed> {
 }
 SetFocused = <function> defined @Blizzard_Communities\CommunitiesList.lua:582
 OnEvent = <function> defined @Blizzard_Communities\CommunitiesList.lua:616
 SetGuildFinder = <function> defined @Blizzard_Communities\CommunitiesList.lua:543
 FavoriteIcon = <unnamed> {
 }
 Name = <unnamed> {
 }
 GuildTabardBackground = <unnamed> {
 }
 UpdateUnreadNotification = <function> defined @Blizzard_Communities\CommunitiesList.lua:500
 IconRing = <unnamed> {
 }
 IsInvitation = <function> defined @Blizzard_Communities\CommunitiesList.lua:592
}
clubInfo = <table> {
 broadcast = "WQs, WQs, WQs, WQs! Oh look new raid, JK ITS IN 3 MONTHS LUL :-)"
 description = "Time written in GMOTD is always CET/Servertime unless specified otherwise."
 avatarId = 0
 clubType = 2
 joinTime = 1531883526000000
 clubId = 2592632
 name = "Method"
 socialQueueingEnabled = false
}
isInvitation = false
isTicket = false
isGuild = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = "CENTER"
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = 10
(*temporary) = 0
(*temporary) = "attempt to index field '_iconBorder' (a nil value)"
Color = <table> {
 highlight = <table> {
 }
 cyan = <table> {
 }
 Lightness = <function> defined @Aurora\Skin\api.lua:832
 grayLight = <table> {
 }
 Saturation = <function> defined @Aurora\Skin\api.lua:824
 button = <table> {
 }
 red = <table> {
 }
 Hue = <function> defined @Aurora\Skin\api.lua:809
 blue = <table> {
 }
 Post = <table> {
 }
 Create = <function> defined @Aurora\Skin\api.lua:852
 white = <table> {
 }
 frame = <table> {
 }
 grayDark = <table> {
 }
 black = <table> {
 }
 green = <table> {
 }
 Pre = <table> {
 }
 yellow = <table> {
 }
 violet = <table> {
 }
 gray = <table> {
 }
}

10x ...Ons\Aurora\SkinBlizzard_ObjectiveTracker.lua:262: Usage: ScenarioObjectiveBlock:SetHeight(height)
[C]: in function `RawSetHeight'
...Ons\Aurora\SkinBlizzard_ObjectiveTracker.lua:262: in function <...Ons\Aurora\SkinBlizzard_ObjectiveTracker.lua:252>
[C]: in function `Update'
...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1073: in function `ObjectiveTracker_Update'
...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:753: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:669>

Locals:
(*temporary) = ScenarioObjectiveBlock {
 0 = <userdata>
 module = <table> {
 }
}
(*temporary) = nil

**Comment by Justw8** [comment]
Posted several errors, some are related to another addon from what I can see (EasyScrap) but there are more.

**Comment by Gethe** [comment]
Make sure you have the most recent version, 8.1.0.0

Blizzard changed the file paths for where addons go, so make sure that the update is in the correct place. If you're using the twitch client, you may need to double check the target path it's using.

**Comment by Justw8** [comment]
You`re right, twitch client fucking me. thanks :)
