### ISSUE TITLE
Some LUA Errors

### ISSUE THREAD

**Issue by BombBang** [Haleth/Aurora#151]
Why popup below LUA errors?

Message: Deferred XML Node object named
L_UIDropDownCustomMenuEntryTemplate already exists

Time: Mon Jan  7 17:43:01 2019
Count: 6

Message: Deferred XML Node object named
L_UIDropDownMenuButtonTemplate already exists

Time: Mon Jan  7 17:43:01 2019
Count: 6

Message: Deferred XML Node object named
L_UIDropDownListTemplate already exists

Time: Mon Jan  7 17:43:01 2019
Count: 6

Message: Deferred XML Node object named
L_UIDropDownMenuTemplate already exists

Time: Mon Jan  7 17:43:01 2019
Count: 6

Message: ...\AddOns\Aurora\Skin\AddOns\Blizzard_ChallengesUI.lua:44: attempt to index local 'Frame' (a nil value)

Time: Mon Jan  7 17:43:04 2019

Count: 1

Stack: ...\AddOns\Aurora\Skin\AddOns\Blizzard_ChallengesUI.lua:44: attempt to index local 'Frame' (a nil value)
...\AddOns\Aurora\Skin\AddOns\Blizzard_ChallengesUI.lua:44: in function `MythicPlusSeasonChangesNoticeTemplate'
...\AddOns\Aurora\Skin\AddOns\Blizzard_ChallengesUI.lua:83: in function `addonModule'
Interface\AddOns\Aurora\Skin\init.lua:130: in function <Interface\AddOns\Aurora\Skin\init.lua:91>
[C]: in function `LoadAddOn'
...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:2644: in function `GetCurrentAffixWeek'
...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:172: in function <...ace\AddOns\MethodDungeonTools\MethodDungeonTools.lua:171>
(tail call): ?

Locals: Frame = nil
(*temporary) = <function> defined @Interface\AddOns\Aurora\Skin\AddOns\Blizzard_ChallengesUI.lua:47
(*temporary) = nil
(*temporary) = "attempt to index local 'Frame' (a nil value)"
Skin = <table> {
 GarrisonFollowerTooltipTemplate = <function> defined @Interface\AddOns\Aurora\Skin\FrameXML\FloatingGarrisonFollowerTooltip.lua:52
 ExpandOrCollapse = <function> defined @Interface\AddOns\Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:37
 HorizontalBarTemplate = <function> defined @Interface\AddOns\Aurora\Skin\FrameXML\UIPanelTemplates.lua:230
 CommunitiesGuildRewardsButtonTemplate = <function> defined @Interface\AddOns\Aurora\Skin\AddOns\Blizzard_Communities.lua:300
 GossipFramePanelTemplate = <function> defined @Interface\AddOns\Aurora\Skin\FrameXML\GossipFrame.lua:41
 GuildChallengeAlertFrameTemplate = <function> defined @Interface\AddOns\Aurora\Skin\FrameXML\AlertFrameSystems.lua:200
 PopupButtonTemplate = <function> defined @Interface\AddOns\Aurora\Skin\FrameXML\ItemButtonTemplate.lua:104
 PetBattleUnitTooltipAuraTemplate = <function> defined @Interface\AddOns\Aurora\Skin\AddOns\Blizzard_PetBattleUI.lua:90
 CommunitiesSettingsButtonTemplate = <function> defined @Interface\AddOns\Aurora\Skin\AddOns\Blizzard_Communities.lua:247
 TooltipBorderedFrameTemplate = <function> defined @Interface\AddOns\Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:307
 AchievementAlertFrameTemplate = <function> defined @Interface\AddOns\Aurora\Skin\FrameXML\AlertFrameSystems.lua:106
 UnitPopupVoiceToggleButtonTemplate = <function> defined @Interface\AddOns\Aurora\Skin\FrameXML\UnitPopupCustomControls.lua:14
 SplashFeatureFrameTemplate = <function> defined @Interface\AddOns\Aurora\Skin\init.lua:47
 ComparisonPlayerTemplate = <function> defined @Interface\AddOns\Aurora\Skin\AddOns\Blizzard_AchievementUI.lua:321
 OptionsListButtonTemplate = <function> defined @Interface\AddOns\Aurora\Skin\FrameXML\OptionsFrameTemplates.lua:32
 MoneyInputFrameTemplate = <function> defined @Interface\AddOns\Aurora\Skin\FrameXML\MoneyInputFrame.lua:17
 HybridScrollBarTemplate = <function> defined @Interface\AddOns\Aurora\Skin\SharedXML\HybridScrollFrame.lua:37
 ProfessionButtonTemplate = <function> defined @Interface\AddOns\Aurora\Skin\FrameXML\SpellBookFrame.lua:156
 InputBoxTemplate = <function> defined @Interface\AddOns\Aurora\Skin\SharedXML\SecureUIPanelTemplates.lua:16
 ContainerFrameHelpBoxTemplate = <function> defined @Interface\AddOns\Aurora\Skin\FrameXML\ContainerFrame.lua:116
 CommunitiesNotificationSettingsDialogTemplate = <function> defined @Interface\AddOns\Aurora\Skin\AddOns\Blizzard_Communities.lua:218
 AchievementSearchPreviewButton = <function> defined @Interface\AddOns\Aurora\Skin\AddOns\Blizzard_AchievementUI.lua:153
 BankItemButtonBagTemplate = <function> defined @Interface\AddOns\Aurora\Skin\FrameXML\BankFrame.lua:49
 CommunitiesTicketManagerScrollFrameTemplate = <function> defined @Interface\AddOns\Aurora\Skin\AddOns\Blizzard_Communities.lua:261
 HybridScrollBarBackgroundTemplate = <function> defined @Interface\AddOns\Aurora\Skin\SharedXML\HybridScrollFrame.lua:23
 MaximizeMinimizeButtonFrameTemplate = <fun

**Comment by Gethe** [comment]
The first four errors you listed are not from Aurora. The other two have been fixed and will be included in the next release.
