### ISSUE TITLE
Error Raises on right click to another character name in chat window (unitpopup.lua)

### ISSUE THREAD

**Issue by karandras2000** [Haleth/Aurora#152]
### Prerequisites ###

* [ ] Are you running the [latest release of Aurora](https://github.com/Haleth/Aurora/releases)? If you're using the Twitch updater, make sure the release type is set to "Release" unless told otherwise.
* **[checked]**

* [ ] Did you [perform a cursory search](https://github.com/Haleth/Aurora/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?
* **[checked, didn't find any comperable issue]**

### Description ###

By do a right l´click on any other char name in a public chat window the popup menu will be opened but raises the following error constantly until you left the popup menu window.

### Steps to Reproduce ###

1. right click on charname in public chat window (like trade chat, common chat, etc.

**Expected behavior:**

do not raise an error for the popup menu

**Actual behavior:**

raises a error for the popup menu constantly

``` lua
265x FrameXML\UnitPopup.lua:1380: Usage: CheckInteractDistance("unit", distIndex)
[C]: in function `CheckInteractDistance'
FrameXML\UnitPopup.lua:1380: in function <FrameXML\UnitPopup.lua:1375>
FrameXML\UnitPopup.lua:1423: in function `UnitPopup_OnUpdate'
[string "*:OnUpdate"]:3: in function <[string "*:OnUpdate"]:1>

Locals:
(*temporary) = nil
(*temporary) = 0
```

### Additional information ###

* Problem started happening recently, didn't happen in an older version of Aurora: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Installed AddOns:**

* WIM
* ElvUI

**Comment by Gethe** [comment]
Have you tried with *just* Aurora?

**Comment by karandras2000** [comment]
Nope. - with only Aurora, the behavior doesn't happen. Problem only raises if "chatter" addon is loaded addionally.

**Comment by Gethe** [comment]
It's probably something to do with Chatter. Try seeing if it happens with just Chatter.

**Comment by karandras2000** [comment]
Yepp, if only Chatter and Aurora are active, it still happens.

**Comment by Gethe** [comment]
This is not an issue with Aurora. It can be done with *just* Chatter. https://www.wowace.com/projects/chatter/issues/1217
