### ISSUE TITLE
Attempt to index field '_auroraIconBorder' (a nil value) on login

### ISSUE THREAD

**Issue by jeremyhill-up** [Haleth/Aurora#155]
### Prerequisites ###

* [x ] Are you running the [latest release of Aurora](https://github.com/Haleth/Aurora/releases)? If you're using the Twitch updater, make sure the release type is set to "Release" unless told otherwise.
* [x ] Did you [perform a cursory search](https://github.com/Haleth/Aurora/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?

### Description ###

I get the following LUA error on login, I don't have to perform any specific action.

### Steps to Reproduce ###

1. Log in to a character with the addon loadout below. 

**Expected behavior:**

No lua error pops up.

**Actual behavior:**

There is a LUA error.

``` lua
Date: 2019-02-05 16:35:00
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Aurora\Skin\FrameXML\LFGFrame.lua line 63:
   attempt to index field '_auroraIconBorder' (a nil value)
Debug:
   Aurora\Skin\FrameXML\LFGFrame.lua:63:
      Aurora\Skin\FrameXML\LFGFrame.lua:53
   [C]: LFGRewardsFrame_SetItemButton()
   ..\FrameXML\LFGFrame.lua:1357: LFGRewardsFrame_UpdateFrame()
   ..\FrameXML\LFDFrame.lua:453: LFDQueueFrameRandom_UpdateFrame()
   ..\FrameXML\LFDFrame.lua:427: LFDQueueFrame_SetType()
   ..\FrameXML\LFDFrame.lua:94:
      ..\FrameXML\LFDFrame.lua:45
Locals:
parentFrame = LFDQueueFrameRandomScrollFrameChildFrame {
 0 = <userdata>
 description = LFDQueueFrameRandomScrollFrameChildFrameDescription {
 }
 numRewardFrames = 2
 xpLabel = LFDQueueFrameRandomScrollFrameChildFrameXPLabel {
 }
 spacer = LFDQueueFrameRandomScrollFrameChildFrameSpacer {
 }
 rewardsLabel = LFDQueueFrameRandomScrollFrameChildFrameRewardsLabel {
 }
 bonusRepFrame = LFDQueueFrameRandomScrollFrameChildFrameBonusRepFrame {
 }
 title = LFDQueueFrameRandomScrollFrameChildFrameTitle {
 }
 encounterList = LFDQueueFrameRandomScrollFrameChildFrameEncounterList {
 }
 randomList = LFDQueueFrameRandomScrollFrameChildFrameRandomList {
 }
 xpAmount = LFDQueueFrameRandomScrollFrameChildFrameXPAmount {
 }
 MoneyReward = LFDQueueFrameRandomScrollFrameChildFrameMoneyReward {
 }
 rewardsDescription = LFDQueueFrameRandomScrollFrameChildFrameRewardsDescription {
 }
}
dungeonID = 1671
index = 2
id = 1
name = ""
texture = 1519434
numItems = 1
rewardType = "item"
rewardID = 160054
quality = 0
shortageIndex = 1
showTankIcon = false
showHealerIcon = true
showDamageIcon = false
parentName = "LFDQueueFrameRandomScrollFrameChildFrame"
frame = LFDQueueFrameRandomScrollFrameChildFrameItem2 {
 0 = <userdata>
 NameFrame = LFDQueueFrameRandomScrollFrameChildFrameItem2NameFrame {
 }
 count = 1
 shortageBorder = LFDQueueFrameRandomScrollFrameChildFrameItem2ShortageBorder {
 }
 shortageIndex = 1
 dungeonID = 1671
 IconOverlay = <unnamed> {
 }
 roleIcon2 = LFDQueueFrameRandomScrollFrameChildFrameItem2RoleIcon2 {
 }
 Count = LFDQueueFrameRandomScrollFrameChildFrameItem2Count {
 }
 IconBorder = <unnamed> {
 }
 roleIcon1 = LFDQueueFrameRandomScrollFrameChildFrameItem2RoleIcon1 {
 }
 hasItem = 1
 Icon = LFDQueueFrameRandomScrollFrameChildFrameItem2IconTexture {
 }
 Name = LFDQueueFrameRandomScrollFrameChildFrameItem2Name {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "2"
(*temporary) = "attempt to index field '_auroraIconBorder' (a nil value)"
skinnedIndex = 3
Skin = <table> {
 AchievementHeaderStatusBarTemplate = <function> defined @Interface\AddOns\Aurora\Skin\AddOns\Blizzard_AchievementUI.lua:240
 CommunitiesGuildRewardsButtonTemplate = <function> defined @Interface\AddOns\Aurora\Skin\AddOns\Blizzard_Communities.lua:291
 TalentRowGlowFrameTemplate = <function> defined @Interface\AddOns\Aurora\Skin\AddOns\Blizzard_TalentUI.lua:97
 PopupButtonTemplate = <function> defined @Interface\AddOns\Aurora\Skin\FrameXML\ItemButtonTemplate.lua:107
 PetBattleUnitTooltipAuraTemplate = <function> defined @Interface\AddOns\Aurora\Skin\AddOns\Blizzard_PetBattleUI.lua:91
 TooltipBorderedFrameTemplate = <function> defined @Interface\AddOns\Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:369
 AchievementAlertFrameTemplate = <function> defined @Interface\AddOns\Aurora\Skin\FrameXML\AlertFrameSystems.lua:106
 UnitPopupVoiceToggleButtonTemplate = <function> defined @Interface\AddOns\Aurora\Skin\FrameXML\UnitPopupCustomControls.lua:14
 InputBoxInstructionsTemplate = <function> defined @Interface\AddOns\Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:483
 ComparisonPlayerTemplate = <function> defined @Interface\AddOns\Aurora\Skin\AddOns\Blizzard_AchievementUI.lua:322
 OptionsListButtonTemplate = <function> defined @Interface\AddOns\Aurora\Skin\FrameXML\OptionsFrameTemplates.lua:32
 MoneyInputFrameTemplate = <function> defined @Interface\AddOns\Aurora\Skin\FrameXML\MoneyInputFrame.lua:17
 HybridScrollBarTemplate = <function> defined @Interface\AddOns\Aurora\Skin\SharedXML\HybridScrollFrame.lua:40
 ChannelButtonHeaderTemplate = <function> defined @Interface\AddOns\Aurora\Skin\AddOns\Blizzard_Channels.lua:35
 QuickJoinToastTemplate = <function> defined @Interface\AddOns\Aurora\Skin\FrameXML\QuickJoinToast.lua:33
 ContainerFrameHelpBoxTemplate = <function> defined @Interface\AddOns\Aurora\Skin\FrameXML\ContainerFrame.lua:59
 CommunitiesNotificationSettingsDialogTemplate = <function> defined @Interface\AddOns\Aurora\Skin\AddOns\Blizzard_Communities.lua:214
 CommunitiesTicketManagerScrollFrameTemplate = <function> defined @Interface\AddOns\Aurora\Skin\AddOns\B

```

### Additional information ###

* Problem started happening recently, didn't happen in an older version of Aurora: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Screenshots and GIFs**

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

**Installed AddOns:**

  BetterFont, v8.1.1
  MoncaiCompare, v7.2.0
  Swatter, v8.0.6162 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.2.9
  AstralKeys, v3.3
  AucAdvanced, v8.0.6122 (SwimmingSeadragon)
  AucFilterBasic, v8.0.6149 (SwimmingSeadragon)
  AucStatHistogram, v8.0.6151 (SwimmingSeadragon)
  AucStatiLevel, v8.0.6155 (SwimmingSeadragon)
  AucStatPurchased, v8.0.6152 (SwimmingSeadragon)
  AucStatSimple, v8.0.6153 (SwimmingSeadragon)
  AucStatStdDev, v8.0.6154 (SwimmingSeadragon)
  AucUtilFixAH, v8.0.6156 (SwimmingSeadragon)
  Aurora, v8.1.0.4
  BagBrother, v
  Bagnon, v8.1.5
  BagnonConfig, v8.1.5
  BuyEmAll, v3.5.1
  CallbackHandler10, v
  DBMCore, v8.1.8
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaCharacterStats, v800r119
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Dominos, v8.1.3
  DominosCast, v
  DominosConfig, v
  DominosEncounter, v
  DominosProgress, v
  DominosRoll, v
  EasyScrap, v19
  ErrorMonster, vv8.0.2
  ExRT, v4000
  GarrisonCommanderBroker, v3.0.1 1.1.0
  gmFonts, v810-2018122201
  InstancePortals, v20
  LibDBIcon10, v
  LibDFramework10, v
  LibSharedMedia30, v3.0-104
  Masque, v8.0.1
  MasqueCaith, v8.0.0
  MasqueCleanUI, v8.1.0
  MasqueOnyx, v8.0.0
  MasqueSerenity, v8.0.0
  Misspelled, v1.7.2
  MoveAnything, v17.0.3
  MythicPlusTimer, v2.5
  Oilvl, v8.0.2
  OmniCC, v8.1.1
  OmniCCConfig, v
  Pawn, v2.2.36
  Prat30, vr1195      
  Prat30Libraries, v
  SexyMap, vv8.0.8
  ShadowedUnitFrames, vv4.2.1
  SharedMedia, v3.1.0-191
  SharedMediaAdditionalFonts, v1.0.26
  SlideBar, v8.0.6160 (SwimmingSeadragon)
  Stubby, v8.0.6161 (SwimmingSeadragon)
  SYH, v
  TellMeWhen, v8.5.9
  TellMeWhenOptions, v
  TidyPlatesThreatPlates, v9.1.2
  TipTac, v18.08.20
  TipTacItemRef, v18.08.12
  TomTom, vv80001-1.0.2
  tullaRange, v8.0.0
  tullaRangeConfig, v
  WarfrontRareTracker, v0.9.7-1
  WorldQuestsList, v85
  BlizRuntimeLib_enUS v8.1.0.80100 <none>
  (ck=799)

**Comment by Gethe** [comment]
Does this still happen with only Aurora enabled?

**Comment by jeremyhill-up** [comment]
Good morning Tim,

Well, I disabled all my addons except Aurora, and went through turning them back on one at a time to figure out which addon interaction was causing problems, and the lua error on login never remanifested itself. Sigh. I apologize for not being able to recreated it, I'll go ahead and close out this ticket.
