### ISSUE TITLE
Giant nameplate font size

### ISSUE THREAD

**Issue by Koviko** [Haleth/Aurora#161]
This is related to #128, however, it's not an issue of conflict with any other addons.

Aurora sets the nameplate font sizes to be much larger than default, increasing:

- the normal nameplates (`SystemFont_NamePlateFixed`) from **9pt** to **14pt**, and
- the large nameplates (`SystemFont_LargeNamePlateFixed`) from **12pt** to **20pt**.

Without Aurora:
![Nameplate font size without Aurora enabled](https://i.imgur.com/xcd3Z80.png)

With Aurora:
![Nameplate font size with Aurora enabled](https://i.imgur.com/SJIJF9M.png)

Changing these values back to their defaults in `Aurora/Skin/FrameXML/Fonts.lua` fixes this issue. I've also found that simply deleting those two lines has the same effect. However, I'm sure a lot of longtime Aurora users would be shocked if, one day, their nameplates were suddenly back down to the normal font size after getting used to the larger one.

Might I propose a "Larger Nameplate Font" option that's checked by default?
Or an adjustable font size option?

**Comment by Gethe** [comment]
Where do you see that `SystemFont_NamePlateFixed` is supposed to be 9pt? The sizes that are used are the same that [Blizz uses in their own file](https://github.com/Gethe/wow-ui-source/blob/live/FrameXML/Fonts.xml#L1841)

**Comment by Koviko** [comment]
It's an assumption I made based on the fact that I get the first image without any addons enabled, and I get the second image with only Aurora enabled.

However, if it is the case that Aurora is setting the defaults as they should be, I'd argue that Aurora doing so is an overstep in case any addon were to set font sizes and Aurora were to overwrite them. The defaults should already be set by the default Blizzard UI without help of Aurora, correct?

I'd like for Aurora to either not set font sizes at all or to give an option to opt-out of it setting font sizes.

**Comment by Obscurrium** [comment]
Same here, the first thing i've noticed using aurora il the font size change. I was only using default UI. I had modify them myself or just comment the section in the file
