### ISSUE TITLE
Black Text when talking to NPC with multiple quests 

### ISSUE THREAD

**Issue by Naab25** [Haleth/Aurora#164]
### Prerequisites ###

* [Yes ] Are you running the [latest release of Aurora](https://github.com/Haleth/Aurora/releases)? If you're using the Twitch updater, make sure the release type is set to "Release" unless told otherwise.
* [Yes ] Did you [perform a cursory search](https://github.com/Haleth/Aurora/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?

### Description ###

It looks normal when getting single quests from npc, but when talking to npc that has multiple quests this pops up and the quest texts are in black 

### Steps to Reproduce ###

1. Talk to any npc that has a quest single quest looks normal
2. Talk to other npc that gives out 2 or more quests and I will get an error and black texts on the quests the NPC is giving 

**Expected behavior:**

Normal Aurora skinned dialogue with expected white text 

**Actual behavior:**

Text turns Black and error pops up 

*lua* (Forgot to copy paste 2nd error sorry but a small part of it is in the screenshot)

Date: 2019-04-14 21:16:42
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Aurora\Skin\FrameXML\QuestFrame.lua line 37:
   attempt to index local 'questTitleButton' (a nil value)
Debug:
   Aurora\Skin\FrameXML\QuestFrame.lua:37:
      Aurora\Skin\FrameXML\QuestFrame.lua:28
   [C]: ?
   [C]: ?
   [C]: Show()
   ..\FrameXML\UIParent.lua:3166:
      ..\FrameXML\UIParent.lua:3161
   [C]: ShowUIPanel()
   ..\FrameXML\QuestFrame.lua:104:
      ..\FrameXML\QuestFrame.lua:23
Locals:
numActiveQuests = 2
(for index) = 1
(for limit) = 2
(for step) = 1
i = 1
questTitleButton = nil
title = "Look To The Stars"
(*temporary) = false
(*temporary) = nil
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'questTitleButton' (a nil value)"
private = <table> {
 isPatch = true
 disabled = <table> {
 }
 uiScale = 1
 API_MINOR = 5
 updateHighlightColor = <function> defined @Interface\AddOns\Aurora\aurora.lua:84
 API_MAJOR = 0
 classColorsHaveChanged = <function> defined @Interface\AddOns\Aurora\aurora.lua:95
 commands = <table> {
 }
 SetupGUI = <function> defined @Interface\AddOns\Aurora\gui.lua:375
 TRIVIAL_QUEST_DISPLAY = "%s (low level)"
 OnLoad = <function> defined @Interface\AddOns\Aurora\aurora.lua:38
 Aurora = <table> {
 }
 debug = <function> defined @Interface\AddOns\Aurora\Skin\init.lua:48
 charClass = <table> {
 }
 FRAME_TITLE_HEIGHT = 27
 isLoaded = true
 backdrop = <table> {
 }
 FrameXML = <table> {
 }
 AddOns = <table> {
 }
 UpdateUIScale = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:482
 nop = <function> defined @Interface\AddOns\Aurora\Skin\init.lua:48
 NORMAL_QUEST_DISPLAY = "%s"
 classColorsInit = <function> defined @Interface\AddOns\Aurora\aurora.lua:110
 SharedXML = <table> {
 }
 font = <table> {
 }
 classColorsReset = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:659
}

### Additional information ###

* Problem started happening recently [No]
, didn't happen in an older version of Aurora: [Yes] this never happened before 8.1
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Screenshots and GIFs**

https://imgur.com/S8q2ttw
https://imgur.com/TW6ScUU

**Installed AddOns:**

AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  AceGUI30SelectablePanel, vv1.0-alpha2
  AdvancedInterfaceOptions, v1.2.9
  Altoholic, vr190
  AtlasLoot, vv8.09.00
  AtlasLootBattleforAzeroth, vv8.09.00
  AtlasLootBurningCrusade, vv8.09.00
  AtlasLootCataclysm, vv8.09.00
  AtlasLootClassic, vv8.09.00
  AtlasLootLegion, vv8.09.00
  AtlasLootMistsofPandaria, vv8.09.00
  AtlasLootWarlordsofDraenor, vv8.09.00
  AtlasLootWrathoftheLichKing, vv8.09.00
  AucAdvanced, v8.1.6201 (SwimmingSeadragon)
  AucFilterBasic, v8.1.6228 (SwimmingSeadragon)
  AucStatHistogram, v8.1.6230 (SwimmingSeadragon)
  AucStatiLevel, v8.1.6234 (SwimmingSeadragon)
  AucStatPurchased, v8.1.6231 (SwimmingSeadragon)
  AucStatSimple, v8.1.6232 (SwimmingSeadragon)
  AucStatStdDev, v8.1.6233 (SwimmingSeadragon)
  AucUtilFixAH, v8.1.6235 (SwimmingSeadragon)
  Aurora, v8.1.5.1
  AutoLootPlus, v1.2.3
  AutoTurnIn, v7.0.9
  BagBrother, v
  Bagnon, v8.1.9
  BagnonBoE, v1.0
  BagnonItemLevel, v1.0
  Bartender4, v4.8.2
  BeanCounter, v8.1.6236 (SwimmingSeadragon)
  BFAInvasionTimer, vv8.1.7
  ClassOrderHallsComplete, v1.34
  DataStore, vr65
  DataStoreAchievements, vr47
  DataStoreAgenda, vr29
  DataStoreAuctions, vr50
  DataStoreCharacters, vr43
  DataStoreContainers, vr59
  DataStoreCrafts, vr82
  DataStoreCurrencies, vr38
  DataStoreGarrisons, vr24
  DataStoreInventory, vr53
  DataStoreMails, vr52
  DataStorePets, vr44
  DataStoreQuests, vr46
  DataStoreReputations, vr43
  DataStoreSpells, vr32
  DataStoreStats, vr31
  DataStoreTalents, vr61
  DBMCore, v@project-version@
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DejaCharacterStats, v800r120
  Enchantrix, v8.1.6237 (SwimmingSeadragon)
  ErrorFilter, vv3.6
  ExtDressingRoom, v1.1.0
  Grail, v099
  GrailAchievements, v011
  GrailQuestsenUS, v27178
  GrailReputations, v007
  GSE, v2404
  GSEGUI, v2404
  GSELDB, v2404
  GTFO, v4.46.17
  HandyNotes, vv1.5.5
  HandyNotesArgus, v0.20.0
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesDraenorTreasures, v1.21
  HandyNotesLegionTreasures, v1
  HandyNotesLunarFestival, vv1.6.1
  HealBot, v8.1.5.1
  HealBotTips, v8.1.5.1
  HiddenArtifactTracker, v
  Informant, v8.1.6246 (SwimmingSeadragon)
  MogIt, v3.9.0
  MogItArtifact, v3.9.0
  MogItLeather, v3.9.0
  MogItOneHanded, v3.9.0
  MogItOther, v3.9.0
  MogItRanged, v3.9.0
  MogItTwoHanded, v3.9.0
  mOnArsWardrobeHelper, v1.18.2
  MoveAnything, v17.0.3
  NPCScan, v8.0.1.13
  Omen, v3.2.0
  Pathfinder, v1.7.2.1
  Prat30, vr1195      
  Prat30Libraries, v
  Quartz, v3.4.0
  ShadowedUnitFrames, vv4.2.2
  Simulationcraft, v1.11.1
  Skada, v1.7.5
  SlideBar, v8.1.6239 (SwimmingSeadragon)
  Spy, v3.5.22
  Stubby, v8.1.6240 (SwimmingSeadragon)
  TheUndermineJournal, v5.4.20190409
  TidyPlatesThreatPlates, v9.1.4
  TomCats, v1.0.7
  TomTom, vv80105-1.0.0
  WeakAuras, v2.11.6
  Wholly, v070
  WorldQuestsList, v87
  XLoot, v8.1-1
  XLootFrame, v8.1-1
  XLootGroup, v8.1-1
  XLootMaster, v8.1-1
  XLootMonitor, v8.1-1
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=bb2)

**Comment by Gethe** [comment]
This was fixed in version 8.1.5.2
