### ISSUE TITLE
[8.1.5.2] Opening raid menu turns entire game area yellow

### ISSUE THREAD

**Issue by twsx** [Haleth/Aurora#165]
### Prerequisites ###

* [X] Are you running the [latest release of Aurora](https://github.com/Haleth/Aurora/releases)? If you're using the Twitch updater, make sure the release type is set to "Release" unless told otherwise.
* [x] Did you [perform a cursory search](https://github.com/Haleth/Aurora/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?

### Description ###

As shown in the GIF below, opening the raid leader menu turns the entire game area yellow-ish. Action bars and the like are no affected, just the entire environment.
Happened to me in raid finder, in case that is relevant.
Can't know for certain that Aurora causes this, obviously, but deactivating the addon or downgrading does resolve the issue.
No LUA error are present when loaded or then the problem occurs.

### Additional information ###

* Problem started happening recently, didn't happen in an older version of Aurora: Yes, downgrading to 8.1.5.1 fixes the problem
* Problem can be reliably reproduced, doesn't happen randomly: Yes, happens every time.

**Screenshots and GIFs**

https://i.imgur.com/JKvrWam.gifv

I only captured the area around the menu, but the entire game area is affected.

**Installed AddOns:**

https://i.imgur.com/W9XAOP8.png

**Comment by L30m4nc3r** [comment]
confirm
