### ISSUE TITLE
Unit Frame Skins gone

### ISSUE THREAD

**Issue by plinus** [Haleth/Aurora#167]
Hi there,

first of all thank you for this addon! I was wondering why the skinning of my unit frames is gone. I'm running the latest version 8.1.5.2 and even when all other addons are deactivated, my unit frames still have the standard design. 

Did i mess up or is it happening to others as well?

![aurora](https://user-images.githubusercontent.com/13884572/57642303-45ade500-75b7-11e9-9bf8-da93e11dc778.png)

**Comment by Gethe** [comment]
Aurora has never has a unit frame skin

**Comment by plinus** [comment]
Thank you for your response! Then it might have been another addon. I'll have a look!

**Comment by plinus** [comment]
@Gethe I looked it up and found a video: 

https://youtu.be/YDrHgqPYCrM

At around 5:40 you can see the dark textured player frame i meant before. Is this coming from the missing textures addon? If so, i file my issue there. Do you know if there have been changes to the unit frames lately?

**Comment by Gethe** [comment]
I'm not sure about any *recent* changes to the unit frames, but they certainly have changed in the four years since the last time Missing Textures has been updated.

If you're using that addon, check if you have that file replaced. It would be a Interface\CharacterFrame\UI-Player-Portrait

**Comment by plinus** [comment]
I’m sure, that the dark texture existed like 2 months ago. I only found two files at Aurora\Skin\FrameXML, which seem to remove the default Blizzard textures. Maybe there were some changes to the character frame? Should be the same for the targeting Frames.



Von: Tim West
Gesendet: Mittwoch, 15. Mai 2019 08:08
An: Haleth/Aurora
Cc: plinus; Author
Betreff: Re: [Haleth/Aurora] Unit Frame Skins gone (#167)

I'm not sure about any recent changes to the unit frames, but they certainly have changed in the four years since the last time Missing Textures has been updated.
If you're using that addon, check if you have that file replaced. It would be a Interface\CharacterFrame\UI-Player-Portrait

**Comment by Gethe** [comment]
I don't know what it could have been. Aurora has never had any such feature, and I just checked Aurora: Missing Textures (which is not directly affiliated with Aurora itself) and it doesn't do that either.

Which means you must have had some other addon installed that changed your unit frames, and maybe *that* addon recently stopped working for some reason.

**Comment by plinus** [comment]
But if you take a closer look at the video, only Aurora is installed. Missing Textures only adds the game external textures like login screen and so on.

**Comment by Gethe** [comment]
Missing Textures also affects textures while playing the game. Maybe on a previous version they darkened the unit frames? I don't know.

Also, that video was made SIX years ago, a lot has changed since then.
