### ISSUE TITLE
SkinBlizzard_TokenUI.lua  --  two error strings.

### ISSUE THREAD

**Issue by kgwium** [Haleth/Aurora#169]
Greetings.

I recently came back to WoW and I am always getting this error message popping up when I go into my currency tab and when I use portals etc.

-----------------------------

2x ...rfaceAurora\SkinBlizzard_TokenUI.lua:34: attempt to perform arithmetic on field 'index' (a nil value)
...rfaceAurora\SkinBlizzard_TokenUI.lua:34: in function <...rfaceAurora\SkinBlizzard_TokenUI.lua:12>
[C]: ?
[C]: in function `TokenFrame_Update'
Blizzard_TokenUI\Blizzard_TokenUI.lua:63: in function <Blizzard_TokenUI\Blizzard_TokenUI.lua:43>
[C]: ?
[C]: in function `Show'
FrameXML\CharacterFrame.lua:35: in function `CharacterFrame_ShowSubFrame'
FrameXML\CharacterFrame.lua:17: in function `ToggleCharacter'
FrameXML\CharacterFrame.lua:48: in function `CharacterFrameTab_OnClick'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals:
buttons = <table> {
 1 = TokenFrameContainerButton1 {
 }
 2 = TokenFrameContainerButton2 {
 }
 3 = TokenFrameContainerButton3 {
 }
 4 = TokenFrameContainerButton4 {
 }
 5 = TokenFrameContainerButton5 {
 }
 6 = TokenFrameContainerButton6 {
 }
 7 = TokenFrameContainerButton7 {
 }
 8 = TokenFrameContainerButton8 {
 }
 9 = TokenFrameContainerButton9 {
 }
 10 = TokenFrameContainerButton10 {
 }
 11 = TokenFrameContainerButton11 {
 }
 12 = TokenFrameContainerButton12 {
 }
 13 = TokenFrameContainerButton13 {
 }
 14 = TokenFrameContainerButton14 {
 }
 15 = TokenFrameContainerButton15 {
 }
 16 = TokenFrameContainerButton16 {
 }
 17 = TokenFrameContainerButton17 {
 }
 18 = TokenFrameContainerButton18 {
 }
 19 = TokenFrameContainerButton19 {
 }
 20 = TokenFrameContainerButton20 {
 }
 21 = TokenFrameContainerButton21 {
 }
 22 = TokenFrameContainerButton22 {
 }
 23 = TokenFrameContainerButton23 {
 }
}
(for index) = 17
(for limit) = 23
(for step) = 1
i = 17
button = TokenFrameContainerButton17 {
 0 = <userdata>
 highlight = TokenFrameContainerButton17Highlight {
 }
 stripe = TokenFrameContainerButton17Stripe {
 }
 _auroraPlus = <unnamed> {
 }
 GetBackdropColor = <function> defined @Aurora\Skin\api.lua:274
 categoryLeft = TokenFrameContainerButton17CategoryLeft {
 }
 SetBackdropBorderColor = <function> defined @Aurora\Skin\api.lua:280
 icon = TokenFrameContainerButton17Icon {
 }
 SetBackdropBorderLayer = <function> defined @Aurora\Skin\api.lua:310
 _auroraMinus = <unnamed> {
 }
 GetBackdropTexture = <function> defined @Aurora\Skin\api.lua:330
 _auroraBackdrop = <table> {
 }
 GetBackdropBorderLayer = <function> defined @Aurora\Skin\api.lua:325
 expandIcon = TokenFrameContainerButton17ExpandIcon {
 }
 SetBackdrop = <function> defined @Aurora\Skin\api.lua:122
 categoryMiddle = TokenFrameContainerButton17CategoryMiddle {
 }
 LinkButton = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @Aurora\Skin\api.lua:304
 name = TokenFrameContainerButton17Name {
 }
 categoryRight = TokenFrameContainerButton17CategoryRight {
 }
 check = TokenFrameContainerButton17Check {
 }
 SetBackdropColor = <function> defined @Aurora\Skin\api.lua:257
 GetBackdrop = <function> defined @Aurora\Skin\api.lua:245
 count = TokenFrameContainerButton17Count {
 }
}
r = 1
g = 1
b = 1
(*temporary) = <function> defined =[C]:-1
(*temporary) = TokenFrameContainerButton17Stripe {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = <table> {
 b = <unnamed> {
 }
 bgBlue = 0.278431
 bgGreen = 0.278431
 borderLayer = "BACKGROUND"
 l = <unnamed> {
 }
 bg = <unnamed> {
 }
 borderAlpha = 1
 tr = <unnamed> {
 }
 tl = <unnamed> {
 }
 options = <table> {
 }
 r = <unnamed> {
 }
 t = <unnamed> {
 }
 bgRed = 0.278431
 bl = <unnamed> {
 }
 borderBlue = 0.400000
 borderRed = 0.400000
 borderSublevel = -7
 br = <unnamed> {
 }
 borderGreen = 0.400000
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = "attempt to perform arithmetic on field 'index' (a nil value)"
Color = <table> {
 highlight = <table> {
 }
 cyan = <table> {
 }
 Lightness = <function> defined @Aurora\Skin\api.lua:562
 grayLight = <table> {
 }
 ruby = <table> {
 }
 Saturation = <function> defined @Aurora\Skin\api.lua:554
 button = <table> {
 }
 Post = <table> {
 }
 orange = <table> {
 }
 red = <table> {
 }
 Hue = <function> defined @Aurora\Skin\api.lua:539
 magenta = <table> {
 }
 blue = <table> {
 }
 lime = <table> {
 }
 frame = <table> {
 }
 white = <table> {
 }
 Create = <function> defined @Aurora\Skin\api.lua:582
 jade = <table> {
 }
 grayDark = <table> {
 }
 violet = <table> {
 }
 black = <table> {
 }
 green = <table> {
 }
 Pre = <table> {
 }
 yellow = <table> {
 }
 marine = <table> {
 }
 gray = <table> {
 }
}
Base = <table> {
 SetHighlight = <function> defined @Aurora\Skin\api.lua:434
 GetSkinList = <function> defined @Aurora\Skin\api.lua:

**Comment by kgwium** [comment]
And now this error pops up when I go into dungeons.

------------------------

13x Blizzard_InspectUI\InspectPVPFrame.lua:80: Usage: UnitFactionGroup("unit" [,checkDisplayRace])
[C]: in function `UnitFactionGroup'
Blizzard_InspectUI\InspectPVPFrame.lua:80: in function `InspectPVPFrame_Update'
Blizzard_InspectUI\InspectPVPFrame.lua:60: in function <Blizzard_InspectUI\InspectPVPFrame.lua:58>

Locals:
(*temporary) = nil

**Comment by Gethe** [comment]
Please create a separate issue for new errors.

**Comment by kgwium** [comment]
This is the new issue that pops up when I changed the code.
Happens when I load into the game from character selection screen..

-----------------------------

6x Aurora\SkinBlizzard_TokenUI.lua:117: 'end' expected (to close 'do' at line 11) near '<eof>'


Locals:
