### ISSUE TITLE
SkinBlizzard_TokenUI.lua error from the new string you provided

### ISSUE THREAD

**Issue by kgwium** [Haleth/Aurora#170]
This is the new issue that pops up when I changed the code with what you provided.
Happens when I load into the game..
I have decided to uninstall the addon for now since it is giving me headaces with these error messages.

-----------------------------

6x Aurora\SkinBlizzard_TokenUI.lua:117: 'end' expected (to close 'do' at line 11) near '<eof>'

Locals:

-----------------------------

![Aurora lua problem](https://user-images.githubusercontent.com/40608423/61643856-3cb25180-ac93-11e9-9fb9-4b9e2d59f9a6.PNG)

**Comment by Gethe** [comment]
You forgot to add an `end`. If you want to try the fix I made, get the alpha version from curse.

**Comment by kgwium** [comment]
nice one,  thanks.

It is working now.
