### ISSUE TITLE
Quest Names are Black

### ISSUE THREAD

**Issue by TalasNetrag** [Haleth/Aurora#177]
With the latest version the quest names are black. The quest-text itself and everything else is fine.
![Anmerkung 2019-09-24 174151](https://user-images.githubusercontent.com/23062877/65527848-a64d1700-def3-11e9-88e9-7426b4dc1ff4.png)

**Comment by Gethe** [comment]
Has your client patched to 8.2.5?

**Comment by TalasNetrag** [comment]
No.

**Comment by Gethe** [comment]
There was a last minute change to that frame and I may not have kept proper compatibility with 8.2.0. It should be fine when you get the patch.
