### ISSUE TITLE
I have Artwork Background (pergament) on some Questframes

### ISSUE THREAD

**Issue by DoubleHighC** [Haleth/Aurora#182]
### Prerequisites ###

* [x ] Are you running the [latest release of Aurora](https://github.com/Haleth/Aurora/releases)? If you're using the Twitch updater, make sure the release type is set to "Release" unless told otherwise.
* [x ] Did you [perform a cursory search](https://github.com/Haleth/Aurora/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?

### Description ###

I have the old "Artwork" Background on several Questframes, but just on few, not all!
Any Ideas? It just happens on Quest get/return frames and not on every get/return frame!

Thank you in advance! :-)

### Steps to Reproduce ###

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**Expected behavior:**

[Describe expected behavior here]

**Actual behavior:**

[Describe observed behavior here]

``` lua
-- If you recived an error, place it here.
```

``` lua
-- Separate them if you have more than one.
```

### Additional information ###

* Problem started happening recently, didn't happen in an older version of Aurora: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]

**Screenshots and GIFs**

![WoWScrnShot_021120_161652](https://user-images.githubusercontent.com/36462582/74250828-7c05c580-4ceb-11ea-86b5-9a020429bc00.jpg)
![WoWScrnShot_021120_161702](https://user-images.githubusercontent.com/36462582/74250829-7c9e5c00-4ceb-11ea-81d6-6d5315a9e717.jpg)

**Installed AddOns:**

[List of installed addons which may conflict with the Aurora skin]

**Comment by DoubleHighC** [comment]
Ohh forgot to mention I disabled all addons except Aurora and the "old" Background as seen in screenshot 1 is still there! ;-)

**Comment by DoubleHighC** [comment]
Sorry again! I sorted it out! I had the alpha release installed! On the regular version it is not happening! Sorry was totally my fault! ;-)

**Comment by Gethe** [comment]
It's honestly fine if you're using the alpha, it's a bug that still needs to be fixed. Just make sure you note that in the issue.
