### ISSUE TITLE
Can't use costum color since last update.

### ISSUE THREAD

**Issue by Fawniie** [Haleth/Aurora#185]
### Prerequisites ###

* [YES ] Are you running the [latest release of Aurora](https://github.com/Haleth/Aurora/releases)? If you're using the Twitch updater, make sure the release type is set to "Release" unless told otherwise.
* [ YES] Did you [perform a cursory search](https://github.com/Haleth/Aurora/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?

### Description ###

[Ever since the most recent update, I'm unable to use costum colors. I have set the color white as a costum color because I think this looks nicer than class-colors but now the class-colors override the costum color.

So in short; costum color option doesn't work anymore for me. It shows classcolors no matter what. On all my characters.]

### Steps to Reproduce ###

1. [Log in]
2. [Turn on custom color option and pick a costum color]
3. [Aurora still shows class-colors, even though you selecter costum color]

**Expected behavior:**

[To be able to use a costum color again]

**Actual behavior:**

[It's showing me class-colors even though I have costum colors enabled]

### Additional information ###

* Problem started happening recently, didn't happen in an older version of Aurora: [Yes]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

**Screenshots and GIFs**

**Installed AddOns:**

[None]

**Comment by Gethe** [comment]
Do you still have this issue? I have not been able to replicate it.
