### ISSUE TITLE
Please give us the option to use "Blizzard Cast Bars"

### ISSUE THREAD

**Issue by bossplayer369** [Haleth/Aurora#191]
Can you please just add the Basic blizzard cast bar, the super trasnparent cast bar is meh, other then that this is the best UI addon imo. Thanks

**Comment by bossplayer369** [comment]
100% If I can use dark basic blizzard cast bars this is hands down the best UI in all of wow

**Comment by Gethe** [comment]
If you like the skin that this addon provides, why would you want the castbar not skinned? I would think that would detract from the look.

Additionally, the disable options that are currently available are due to conflicts with other addons that use the original Blizzard elements. Castbars however typically disable the Blizz versions and create their own, so there wouldn't be a conflict.

**Comment by bossplayer369** [comment]
I dark everything out for your addon, The transparent is not fitting. It would be nice to have the option to use blizzard default cast bars

**Comment by bossplayer369** [comment]
I dark everything out with the addon, the transparent cast bar is not fitting and is hard to see. It's just not great. All I'am doing is giving feedback to make the addon better

**Comment by bossplayer369** [comment]
But at the same time, this is still the best UI out there. Hands down. 1 minor tweek to make all the bars basic blizzard bars and that would be prime

**Comment by bossplayer369** [comment]
But at the same time, Aurora is the best UI out there. Hands down. 1 minor tweek to make all the bars basic blizzard bars and that would be prime

**Comment by Mattycoolboi** [comment]
I enjoy everything about this addon as well except that there seems to be conflicting issues with the castbars. I use classiccastbars and when I have aurora enabled it causes a big white flash around the target castbar when they complete a cast. If there was any way to toggle the castbar options inside Aurora (I might also just be unaware of how to do so), it would be a big upgrade.
