### ISSUE TITLE
Please help me make the Aurora XP bar disappear. 

### ISSUE THREAD

**Issue by Elcampesinow** [Haleth/Aurora#199]
Hello,

I am running the latest version of Aurora in World of Warcraft, and I´d like to know how to make the experience bar disappear. I want to use a different, separate add-on to change the experience bar.

I don´t see any option or command that will allow me to make the experience bar disappear once Aurora is installed or running. I don´t even see an option regarding the skinning of the experience bar.

Any and all help is appreciated.

Sincerely,

I grateful user of your add-on.

**Comment by Gethe** [comment]
The XP bar is part of the main menu skin, so you can disable that to also disable the XP bar skin.

**Comment by Elcampesinow** [comment]
"The XP bar is part of the main menu skin, so you can disable that to also disable the XP bar skin."
- Gethe

Hi, Thank you for the reply.

NOW: I havan´t seen an option under WoW to make the XP bar disappear.

What button or shortcut do I use to do this, please?

**Comment by Elcampesinow** [comment]
Update: Disabling the Main Menu skin, does not affect the XP bar. Only turning off Aurora completely, by deselecting it from Add-ons, makes the bar go away.

I don´t want to part with Aurora completely. Any other options, so I can use Experiencer as my XP bar and not have two bars over lapping?
