### ISSUE TITLE
LUA error i get since last update 8.3.0.7

### ISSUE THREAD

**Issue by Obscurrium** [Haleth/Aurora#201]
I got this at connection :

4x ...rfaceAurora\Skin\FrameXML\UIDropDownMenu.lua:129: attempt to call method 'GetButtonColor' (a nil value)
[string "@Aurora\Skin\FrameXML\UIDropDownMenu.lua"]:129: in function <...rfaceAurora\Skin\FrameXML\UIDropDownMenu.lua:128>
[string "=[C]"]: in function `UIDropDownMenu_EnableDropDown'
[string "@HandyNotes\HandyNotes_EditFrame.lua"]:141: in main chunk

Locals:
dropDown = HandyNotes_IconDropDown {
 0 = <userdata>
 Right = HandyNotes_IconDropDownRight {
 }
 Left = HandyNotes_IconDropDownLeft {
 }
 Text = HandyNotes_IconDropDownText {
 }
 Button = HandyNotes_IconDropDownButton {
 }
 Icon = HandyNotes_IconDropDownIcon {
 }
 Middle = HandyNotes_IconDropDownMiddle {
 }
 noResize = 1
}
(*temporary) = <function> defined @Aurora\Skin\deprecated.lua:44
(*temporary) = HandyNotes_IconDropDown {
 0 = <userdata>
 Right = HandyNotes_IconDropDownRight {
 }
 Left = HandyNotes_IconDropDownLeft {
 }
 Text = HandyNotes_IconDropDownText {
 }
 Button = HandyNotes_IconDropDownButton {
 }
 Icon = HandyNotes_IconDropDownIcon {
 }
 Middle = HandyNotes_IconDropDownMiddle {
 }
 noResize = 1
}
(*temporary) = nil
(*temporary) = HandyNotes_IconDropDownButton {
 NormalTexture = HandyNotes_IconDropDownButtonNormalTexture {
 }
 OnLeave = <function> defined @FrameXML\UIDropDownMenuTemplates.lua:13
 HighlightTexture = HandyNotes_IconDropDownButtonHighlightTexture {
 }
 HandlesGlobalMouseEvent = <function> defined @SharedXML\DropDownToggleButton.lua:7
 PushedTexture = HandyNotes_IconDropDownButtonPushedTexture {
 }
 DisabledTexture = HandyNotes_IconDropDownButtonDisabledTexture {
 }
 OnMouseDown = <function> defined @FrameXML\UIDropDownMenuTemplates.lua:17
 0 = <userdata>
 OnEnter = <function> defined @FrameXML\UIDropDownMenuTemplates.lua:9
 OnLoad_Intrinsic = <function> defined @SharedXML\DropDownToggleButton.lua:3
}
(*temporary) = "attempt to call method 'GetButtonColor' (a nil value)"
Base = <table> {
 SetHighlight = <function> defined @Aurora\Skin\api.lua:527
 SetTexture = <function> defined @Aurora\Skin\api.lua:568
 Post = <table> {
 }
 CreateBackdrop = <function> defined @Aurora\Skin\api.lua:405
 SetBackdrop = <function> defined @Aurora\aurora.lua:124
 CreateColor = <function> defined @Aurora\Skin\color.lua:98
 Pre = <table> {
 }
 RegisterTexture = <function> defined @Aurora\Skin\api.lua:578
 IsTextureRegistered = <function> defined @Aurora\Skin\api.lua:564
 CropIcon = <function> defined @Aurora\Skin\api.lua:78
 GetAddonSkins = <function> defined @Aurora\Skin\api.lua:55
 AddSkin = <function> defined @Aurora\Skin\api.lua:39
 SetFont = <function> defined @Aurora\Skin\api.lua:426
 SetBackdropColor = <function> defined @Aurora\Skin\deprecated.lua:44
}

Thnx for reading.

### Prerequisites ###

* [x] Are you running the [latest release of Aurora](https://github.com/Haleth/Aurora/releases)? If you're using the Twitch updater, make sure the release type is set to "Release" unless told otherwise.
* [x] Did you [perform a cursory search](https://github.com/Haleth/Aurora/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?

### Description ###

[Short description of problem here]

### Steps to Reproduce ###

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**Expected behavior:**

[Describe expected behavior here]

**Actual behavior:**

[Describe observed behavior here]

``` lua
-- If you recived an error, place it here.
```

``` lua
-- Separate them if you have more than one.
```

### Additional information ###

* Problem started happening recently, didn't happen in an older version of Aurora: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]

**Screenshots and GIFs**

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

**Installed AddOns:**

[List of installed addons which may conflict with the Aurora skin]

**Comment by Obscurrium** [comment]
hello,

why close this without any answer plz ? still getting this error everyday every loggin.

Thanks in advance

**Comment by Gethe** [comment]
It was closed with a link to the commit that fixed it. It's automated. Also, I haven't made an official release yet. if you want to test this fix, you can download the alpha version from curse.
