### ISSUE TITLE
#beta error

### ISSUE THREAD

**Issue by gaveer** [Haleth/Aurora#207]
27x Aurora\Skin\backdrop.lua:350: attempt to call method 'SetBackdropColor' (a nil value)
[string "@Aurora\Skin\backdrop.lua"]:350: in function <Aurora\Skin\backdrop.lua:346>
[string "=(tail call)"]: ?
[string "@Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua"]:313: in function <...Ons\Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:309>
[string "=[C]:"]: in function 'PanelTemplates_SelectTab'
[string "@SharedXML\SharedUIPanelTemplates.lua"]:427: in function 'PanelTemplates_UpdateTabs'
[string "@SharedXML\SharedUIPanelTemplates.lua"]:408: in function 'PanelTemplates_SetTab'
[string "@Blizzard_InspectUI\Blizzard_InspectUI.lua"]:115: in function 'InspectSwitchTabs'
[string "@Blizzard_InspectUI\Blizzard_InspectUI.lua"]:12: in function 'InspectFrame_Show'
[string "@FrameXML\UIParent.lua"]:1176: in function 'InspectUnit'
[string "@FrameXML\UnitPopup.lua"]:1764: in function 'func'
[string "@SharedXML\UIDropDownMenu.lua"]:905: in function 'UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>
[string "=[C]:"]: ?

**Comment by Gethe** [comment]
This is fixed in the alpha version.
