### ISSUE TITLE
New Error  , Beta 9.0.1

### ISSUE THREAD

**Issue by gaveer** [Haleth/Aurora#208]
4x Aurora\Skin\backdrop.lua:194: attempt to index field '?' (a nil value)
[string "@Aurora\Skin\backdrop.lua"]:194: in function 'ApplyBackdrop'
[string "@SharedXML\Backdrop.lua"]:397: in function <SharedXML\Backdrop.lua:385>
[string "=(tail call)"]: ?
[string "@Aurora\Skin\backdrop.lua"]:519: in function 'CreateBackdrop'
[string "@Aurora\Skin\Blizzard_GarrisonTemplates-1.0.lua"]:54: in function 'GarrisonUITemplate'
[string "@Aurora\Skin\Blizzard_GarrisonUI-1.0.lua"]:611: in function 'addonModule'
[string "@Aurora\Skin\init.lua"]:253: in function <Aurora\Skin\init.lua:210>
[string "=[C]:"]: in function 'LoadAddOn'
[string "@FrameXML\UIParent.lua"]:493: in function 'UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:683: in function 'Garrison_LoadUI'
[string "@FrameXML\UIParent.lua"]:1923: in function <FrameXML\UIParent.lua:1250>

**Comment by gaveer** [comment]
30x ...face\Aurora\Skin\FrameXML\ReputationFrame.lua:17: bad argument #1 to '(for generator)' (table expected, got nil)
[string "=[C]:"]: in function '(for generator)'
[string "@Aurora\Skin\FrameXML\ReputationFrame.lua"]:17: in function <...face\Aurora\Skin\FrameXML\ReputationFrame.lua:16>
[string "=[C]:"]: in function 'ReputationFrame_SetRowType'
[string "@FrameXML\ReputationFrame.lua"]:198: in function <FrameXML\ReputationFrame.lua:110>
[string "=[C]:"]: in function 'ReputationFrame_Update'
[string "@FrameXML\ReputationFrame.lua"]:20: in function <FrameXML\ReputationFrame.lua:18>
[string "=[C]:"]: ?
[string "=[C]:"]: in function 'Show'
[string "@FrameXML\UIParent.lua"]:2878: in function 'SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2723: in function 'ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2591: in function <FrameXML\UIParent.lua:2587>
[string "=[C]:"]: in function 'SetAttribute'
[string "@FrameXML\UIParent.lua"]:3442: in function 'ShowUIPanel'
[string "@FrameXML\CharacterFrame.lua"]:21: in function 'ToggleCharacter'
[string "TOGGLECHARACTER2"]:1: in function <[string "TOGGLECHARACTER2"]:1>

**Comment by gaveer** [comment]
28x Aurora\Skin\backdrop.lua:530: attempt to call method 'SetBackdropColor' (a nil value)
[string "@Aurora\Skin\backdrop.lua"]:530: in function <Aurora\Skin\backdrop.lua:526>
[string "=(tail call)"]: ?
[string "@Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua"]:313: in function <...Ons\Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua:309>
[string "=[C]:"]: in function 'PanelTemplates_SelectTab'
[string "@SharedXML\SharedUIPanelTemplates.lua"]:427: in function 'PanelTemplates_UpdateTabs'
[string "@SharedXML\SharedUIPanelTemplates.lua"]:408: in function 'PanelTemplates_SetTab'
[string "@Blizzard_InspectUI\Blizzard_InspectUI.lua"]:115: in function 'InspectSwitchTabs'
[string "@Blizzard_InspectUI\Blizzard_InspectUI.lua"]:12: in function 'InspectFrame_Show'
[string "@FrameXML\UIParent.lua"]:1176: in function 'InspectUnit'
[string "@FrameXML\UnitPopup.lua"]:1764: in function 'func'
[string "@SharedXML\UIDropDownMenu.lua"]:905: in function 'UIDropDownMenuButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>
[string "=[C]:"]: ?

**Comment by gaveer** [comment]
1x Usage: local spellID = C_SpecializationInfo.GetSpellsDisplay(specializationID)
[string "=[C]:"]: in function 'GetSpellsDisplay'
[string "@Aurora\Skin\Blizzard_TalentUI.lua"]:68: in function <...face\Aurora\Skin\Blizzard_TalentUI.lua:46>
[string "=[C]:"]: in function 'PlayerTalentFrame_UpdateSpecFrame'
[string "@Blizzard_TalentUI\Blizzard_TalentUI.lua"]:396: in function 'PlayerTalentFrame_Refresh'
[string "@Blizzard_TalentUI\Blizzard_TalentUI.lua"]:305: in function <...rface\Blizzard_TalentUI\Blizzard_TalentUI.lua:298>

**Comment by gaveer** [comment]
1x ...Aurora\Skin\FrameXML\TalentFrameTemplates.lua:15: attempt to index local 'Button' (a nil value)
[string "@Aurora\Skin\FrameXML\TalentFrameTemplates.lua"]:15: in function 'PvpTalentSlotTemplate'
[string "@Aurora\Skin\FrameXML\TalentFrameTemplates.lua"]:23: in function 'PvpTalentTrinketSlotTemplate'
[string "@Aurora\Skin\Blizzard_TalentUI.lua"]:282: in function 'addonModule'
[string "@Aurora\Skin\init.lua"]:253: in function <Aurora\Skin\init.lua:210>
[string "=[C]:"]: in function 'LoadAddOn'
[string "@FrameXML\UIParent.lua"]:493: in function 'UIParentLoadAddOn'
[string "@FrameXML\UIParent.lua"]:576: in function 'TalentFrame_LoadUI'
[string "@FrameXML\UIParent.lua"]:841: in function 'ToggleTalentFrame'
[string "TOGGLETALENTS"]:1: in function <[string "TOGGLETALENTS"]:1

**Comment by gaveer** [comment]
35x Aurora\Skin\backdrop.lua:238: attempt to index field 'backdropInfo' (a nil value)
[string "@Aurora\Skin\backdrop.lua"]:238: in function 'SetBackdropBorderColor'
[string "@Aurora\Skin\backdrop.lua"]:531: in function <Aurora\Skin\backdrop.lua:526>
[string "=(tail call)"]: ?
[string "@Aurora\Skin\api.lua"]:171: in function <Aurora\Skin\api.lua:163>
[string "@Aurora\Skin\api.lua"]:194: in function <Aurora\Skin\api.lua:191>
[string "@Aurora\Skin\api.lua"]:211: in function <Aurora\Skin\api.lua:209>
[string "=[C]:"]: in function 'LockHighlight'
[string "@Blizzard_TradeSkillUI\Blizzard_TradeSkillRecipeButton.lua"]:198: in function 'SetSelected'
[string "@Blizzard_TradeSkillUI\Blizzard_TradeSkillRecipeList.lua"]:433: in function 'RefreshDisplay'
[string "@Blizzard_TradeSkillUI\Blizzard_TradeSkillRecipeList.lua"]:479: in function 'SetSelectedRecipeID'
[string "@Blizzard_TradeSkillUI\Blizzard_TradeSkillRecipeList.lua"]:303: in function 'VerifySelection'
[string "@Blizzard_TradeSkillUI\Blizzard_TradeSkillRecipeList.lua"]:69: in function <...zzard_TradeSkillUI\Blizzard_TradeSkillRecipeList.lua:50>

**Comment by Gethe** [comment]
Please keep different errors in separate issues

**Comment by gaveer** [comment]
Blizzard_GarrisonTemplates ~ReputationFrame ~Blizzard_TradeSkillRecipeButton~Blizzard_TalentUI~TalentFrameTemplates
**all on aurora\Skin**

**Comment by Gethe** [comment]
Yes, those should all be separate issues. You already have one for the rep frame, please make separate issue for the others.

**Comment by gaveer** [comment]
well i give you everything 👍
