### ISSUE TITLE
Missing frame sides (BfA)

### ISSUE THREAD

**Issue by JuliaFrankiss** [Haleth/Aurora#210]
Hi and thanks for your addon.

I got this issue with or without all addons
![issue2](https://user-images.githubusercontent.com/68965386/88839262-7e010980-d1e3-11ea-8ab3-f325c0ec353d.png)
![issue1](https://user-images.githubusercontent.com/68965386/88839023-13e86480-d1e3-11ea-8309-0272fa81439b.png)
![issue3](https://user-images.githubusercontent.com/68965386/88839371-a2f57c80-d1e3-11ea-8200-17fea02fd51a.png)

And one more thing. When you press this button, the list is too transparent to read.
![issue4](https://user-images.githubusercontent.com/68965386/88839943-65452380-d1e4-11ea-8f7c-e03a370fedff.png)

**Comment by Gethe** [comment]
The borders thing is a pixel positioning issue with the way Blizz renders the UI. I've done as much as I can to minimize it.
