### ISSUE TITLE
Beta error

### ISSUE THREAD

**Issue by Dudditz** [Haleth/Aurora#211]
Getting this error when logging in. No other addons.

Message: Interface\AddOns\Aurora\Skin\util.lua:125: hooksecurefunc(): UpdatedSelectedHighlight is not a function
Time: Mon Aug 10 22:11:04 2020
Count: 1
Stack: Interface\AddOns\Aurora\Skin\util.lua:125: hooksecurefunc(): UpdatedSelectedHighlight is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface\AddOns\Aurora\Skin\util.lua"]:125: in function `Mixin'
[string "@Interface\AddOns\Aurora\Skin\SharedXML\ScrollList.lua"]:52: in function `?'
[string "@Interface\AddOns\Aurora\Skin\init.lua"]:232: in function <Interface\AddOns\Aurora\Skin\init.lua:210>

Locals:

**Comment by Gethe** [comment]
Fixed in ac0b47b84d678c43e77067f3533ae0022fd097ab
