### ISSUE TITLE
HelpFrame is now HelpBrowser

### ISSUE THREAD

**Issue by liquidbase** [Haleth/Aurora#216]
### Prerequisites ###

* [ ] Are you running the [latest release of Aurora](https://github.com/Haleth/Aurora/releases)? If you're using the Twitch updater, make sure the release type is set to "Release" unless told otherwise.
* [X] Did you [perform a cursory search](https://github.com/Haleth/Aurora/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?

### Description ###

The following error appears directly when logging in since the last build in the Shadowlands Beta. Version of Aurora is the current Alpha from GitHub.

### Steps to Reproduce ###

1. Login on Beta or PTR

``` lua
Message: Interface\AddOns\Aurora\Skin\FrameXML\HelpFrame.lua:51: hooksecurefunc(): HelpFrame_SetSelectedButton is not a function
Time: Mon Sep 21 13:23:52 2020
Count: 1
Stack: Interface\AddOns\Aurora\Skin\FrameXML\HelpFrame.lua:51: hooksecurefunc(): HelpFrame_SetSelectedButton is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface\AddOns\Aurora\Skin\FrameXML\HelpFrame.lua"]:51: in function `?'
[string "@Interface\AddOns\Aurora\Skin\init.lua"]:232: in function <Interface\AddOns\Aurora\Skin\init.lua:210>

Locals: 
```

### Additional information ###

* Blizzard has renamed the HelpFrame to HelpBrowser.

**Comment by Gethe** [comment]
Fixed in e2fa4503
