### ISSUE TITLE
No Aurora skin in Pet Battle UI after 9.0.1.0 update

### ISSUE THREAD

**Issue by Kithhurrn** [Haleth/Aurora#219]
The Pet Battle UI was using the Aurora skinning last night. I updated addons before logging in today and Aurora was updated to the latest release and now I'm getting the default Blizz skinning for Pet Battle UI. Not finding any specific setting for this in Aurora. Also noticed that the Classic Quest Log addon is using Aurora's skinning but the text is a dark color and nearly impossible to read because it's too dark against the background. Again I can find no setting to change text color. Am using Masque's "Dark" plugin but everything was fine until the update and no other addons updated today so the only change has been with Aurora.

**Comment by InfernalDark** [comment]
I lost all of my skins, char window etc. So I will just revert back to earlier version for now.

**Comment by SaturosZed** [comment]
> I lost all of my skins, char window etc. So I will just revert back to earlier version for now.

same

**Comment by Barthezzcz** [comment]
yep. its completely broken, nice update

**Comment by Gethe** [comment]
You sorry about that. I changed the file structure a while ago, but forgot to fix the build script. Will be fixed soon.
