### ISSUE TITLE
no new Aurora missing texture

### ISSUE THREAD

**Issue by CrisReus** [Haleth/Aurora#220]
I love this UI, I think it's great more then others, we should say thanks for your work.
but, Aurora missing texture hasn't been updated for a long time.
no new AMT?
or which texture I should use, I don't like  ElvUI.

**Comment by Gethe** [comment]
I don't maintain the missing textures addon. What parts of the UI are missing?

**Comment by CrisReus** [comment]
oh sorry
the package name is AuroraMissingTextures_238
I downloaded it on 1.16 2016 on wowinterface

**Comment by Gethe** [comment]
Yes, I'm familiar with the package. What parts of the UI are messed up with it not being updated?

My goal is that you wouldn't need such an addon.

**Comment by CrisReus** [comment]
At present, the server is under maintenance and I can't give accurate feedback. 
I will try to do some collection after the server is open. 
I think it will be a long-term work.

**Comment by CrisReus** [comment]
I think I should apologize for what I said before.
I didn't encounter many bugs.
just many buttons, and the main interface of talent.
but it's not affect for use.
thanks for your work again.
