### ISSUE TITLE
LUA error after patch

### ISSUE THREAD

**Issue by InfernalDark** [Haleth/Aurora#225]
Message: Interface\AddOns\Aurora\Skin\deprecated.lua:303: <unnamed>:SetFrameLevel(): Passed negative frame level: -1
Time: Wed Oct 14 19:19:04 2020
Count: 1
Stack: Interface\AddOns\Aurora\Skin\deprecated.lua:303: <unnamed>:SetFrameLevel(): Passed negative frame level: -1
[string "=[C]"]: in function `SetFrameLevel'
[string "@Interface\AddOns\Aurora\Skin\deprecated.lua"]:303: in function `SetBD'
[string "@Interface\AddOns\Aurora\Skin\AddOns\Blizzard_BarbershopUI.lua"]:16: in function `addonModule'
[string "@Interface\AddOns\Aurora\Skin\init.lua"]:247: in function <Interface\AddOns\Aurora\Skin\init.lua:211>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:610: in function `BarberShopFrame_LoadUI'
[string "@Interface\FrameXML\UIParent.lua"]:1953: in function <Interface\FrameXML\UIParent.lua:1258>

Locals: (*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = -1

**Comment by Gethe** [comment]
Fixed with 9.0.1.4
