### ISSUE TITLE
Question about calendar

### ISSUE THREAD

**Issue by liquidbase** [Haleth/Aurora#228]
I have a question about the calendar.
Is it intended that the frame for CalendarToday is larger than the actual day field?
What I mean can be seen on the screenshot.

**Screenshots and GIFs**

![Screenshot](https://i.imgur.com/ZzEpHRU.jpeg)

**Comment by Lunaeria** [comment]
Just came here to ask this, though I think it's bugged because if you notice the edges/background of the calendar don't quite line up, either. Particularly noticeable against a light-coloured background.

**Comment by agentschmitt** [comment]
i have this issue too
