### ISSUE TITLE
quest text hard to read

### ISSUE THREAD

**Issue by Axejess** [Haleth/Aurora#230]
Seems text from quest log is hard to read. This is because of the white text instead of the black default.
Or it is because of the brownish/yellowish background that isn't replaced by a black background.

I couldn't find a option to either replace one of the two.

**Comment by zofia1347** [comment]
I have this issue as well! Quest text is white and there is no Aurora skin on the quest itself making it very difficult to read.

![image](https://user-images.githubusercontent.com/73046345/96374244-59536880-1126-11eb-8d2d-d2289a9e1109.png)
