### ISSUE TITLE
Some frames are not skinned properly

### ISSUE THREAD

**Issue by hobulian** [Haleth/Aurora#234]
### Prerequisites ###

* [x] Are you running the [latest release of Aurora](https://github.com/Haleth/Aurora/releases)? If you're using the Twitch updater, make sure the release type is set to "Release" unless told otherwise.
* [x] Did you [perform a cursory search](https://github.com/Haleth/Aurora/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?

### Description ###

**Screenshots and GIFs**
Some are fixed but others are still not skinned on 11.07 after 9.0.1.5-2-gfcabb6c

What I've checked 
1. Barber Shop buttons are not skinned or broken
They are normal at first but when button changes it goes broke
https://imgur.com/a/nGoEbSG

Only aurora enabled and made no custom textures in Interface folder. It still happened. It's skinned at first when i enter barbershop interface but when i change appearance options it goes broke like screenshot uploaded.. but when clicked it is skinned as normal.

It seems that there are 3 frames at each of 3 buttons(Accept / Cancle / Reset) but Center one may not be skinned
https://imgur.com/a/ph9ESQ6

### Additional information ###

* Problem started happening recently, didn't happen in an older version of Aurora: [Yes/No]
yes

* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]
yes

**Installed AddOns:**
It happens when i only turn Aurora on

**Comment by hobulian** [comment]
Also void storage skin broken

https://imgur.com/a/dB3zMbB

**Comment by hobulian** [comment]
Auction / Interface frame there are white bg.. is it intended?

https://imgur.com/a/nmyJtFi

**Comment by hobulian** [comment]
https://imgur.com/a/LKtRKqm

**Comment by hobulian** [comment]
Also void storage skin broken
https://imgur.com/a/dB3zMbB

Auction / Interface frame there are white bg.. is it intended?
https://imgur.com/a/nmyJtFi

Barber Shop buttons are not skinned or broken
https://imgur.com/a/nGoEbSG

**Comment by hobulian** [comment]
Still Going on 10.25 after 9.0.1.4-15-gb9f9aaf

Barber Shop buttons are not skinned or broken
https://imgur.com/a/nGoEbSG

Quest progress bar on objective track frame
https://imgur.com/a/e568NcA

BFA Mission Frame and Garrison mission frame
https://imgur.com/a/fbDPfPz
https://imgur.com/a/wEKvtZE

**Comment by Gethe** [comment]
I have not seen that issue in the barber shop. Can you see if it still happens with only Aurora enabled?

**Comment by hobulian** [comment]
I've checked with only aurora enabled and made no custom textures in Interface folder. It still happened. 
It's skinned at first when i enter barbershop interface but when i change appearance options it goes broke like screenshot uploaded

**Comment by hobulian** [comment]
10.27 
CommunitiesFrame.ChatEditBox border is not fit to it's frame.
https://imgur.com/a/ndRzvGo

**Comment by hobulian** [comment]
11.01
Didn't captured but when i opened n'zoth's main assault reward cache. Gold reward frame was over fit.
