### ISSUE TITLE
NPC dialogue frame not skinned in Classic

### ISSUE THREAD

**Issue by zlmn** [Haleth/Aurora#235]
### Prerequisites ###

* [x ] Are you running the [latest release of Aurora](https://github.com/Haleth/Aurora/releases)? If you're using the Twitch updater, make sure the release type is set to "Release" unless told otherwise.
* [x ] Did you [perform a cursory search](https://github.com/Haleth/Aurora/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?

### Description ###

When I install the latest release version for classic, the NPC dialogue/quest frame is no longer skinned properly. Everything else seems to work fine.

### Steps to Reproduce ###

1. install latest classic version
2. talk to NPC

**Expected behavior:**

window should be skinned with the aurora black transparent backdrop

**Actual behavior:**

window uses the default blizzard backdrop. Some of the text in the window is still white like I'd expect with Aurora

``` lua
-- If you recived an error, place it here.
```

``` lua
-- Separate them if you have more than one.
```

### Additional information ###

* Problem started happening recently, didn't happen in an older version of Aurora: [Yes/No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes/No]

**Screenshots and GIFs**

![Screenshots and GIFs which follow reproduction steps to demonstrate the problem](url)

**Installed AddOns:**

[List of installed addons which may conflict with the Aurora skin]

**Comment by Gethe** [comment]
Are you still seeing this? I looked and could find any NPC dialogs that were not skinned.

**Comment by zlmn** [comment]
Sorry, I forgot that I posted here haha. This was fixed in one of the updates in the past month, I'm afraid I can't remember which. Thanks for the time you put into this!

**Comment by Gethe** [comment]
It's all good, just checking in
