### ISSUE TITLE
Skin for Ratings button at Gamemenu frame [korean client]

### ISSUE THREAD

**Issue by hobulian** [Haleth/Aurora#239]
### Prerequisites ###

* [x] Are you running the [latest release of Aurora](https://github.com/Haleth/Aurora/releases)? If you're using the Twitch updater, make sure the release type is set to "Release" unless told otherwise.
* [x] Did you [perform a cursory search](https://github.com/Haleth/Aurora/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your bug or enhancement is already reported?

### Description ###
In korean client there's Ratings button at Gamemenu frame
https://imgur.com/a/sB7MxDl

I've added  "Ratings = true," at button table at GameMenuFrame.lua so it is skinned like in screenshot. But by default it's not skinned. So can you add some locale options for this ratings button at GameMenuFrame.lua?

### Additional information ###

 local buttons = {
        Help = true,
        WhatsNew = true,
        Store = true,

        Options = true,
        UIOptions = true,
        Keybindings = true,
        Macros = true,
        Addons = true,
	**>> Ratings = true,**

        Logout = true,
        Quit = true,

        Continue = true,
    }

**Comment by Gethe** [comment]
Fixed in 46fe910d9039b38a22a676093728c84c45e9ffb8
