### ISSUE TITLE
Error when opening Pettraining-Window in Classic WoW

### ISSUE THREAD

**Issue by Liijin** [Haleth/Aurora#240]
Hello, ill get this Error when im Opening the Pettraining-Window on my Hunter in WoW-Classic.

Message: ...rface\AddOns\Aurora\Skin\AddOns\Blizzard_CraftUI.lua:60: Usage: GetItemInfo(itemID|"name"|"itemlink")
Time: Sat Nov  7 17:25:49 2020
Count: 2
Stack: ...rface\AddOns\Aurora\Skin\AddOns\Blizzard_CraftUI.lua:60: Usage: GetItemInfo(itemID|"name"|"itemlink")
[C]: ?
[C]: in function `GetItemInfo'
...rface\AddOns\Aurora\Skin\AddOns\Blizzard_CraftUI.lua:60: in function <...rface\AddOns\Aurora\Skin\AddOns\Blizzard_CraftUI.lua:51>
[C]: in function `CraftFrame_SetSelection'
...terface\AddOns\Blizzard_CraftUI\Blizzard_CraftUI.lua:36: in function `CraftFrame_OnShow'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[C]: in function `Show'
Interface\FrameXML\UIParent.lua:2087: in function `SetUIPanel'
Interface\FrameXML\UIParent.lua:1932: in function `ShowUIPanel'
Interface\FrameXML\UIParent.lua:1793: in function <Interface\FrameXML\UIParent.lua:1789>
[C]: in function `SetAttribute'
Interface\FrameXML\UIParent.lua:2535: in function `ShowUIPanel'
...
(tail call): ?
(tail call): ?
(tail call): ?
...\TradeSkillMaster\LibTSM\Util\FSMClasses\Machine.lua:178: in function <...\TradeSkillMaster\LibTSM\Util\FSMClasses\Machine.lua:160>
(tail call): ?
...\TradeSkillMaster\LibTSM\Util\FSMClasses\Machine.lua:136: in function <...\TradeSkillMaster\LibTSM\Util\FSMClasses\Machine.lua:114>
(tail call): ?
...\AddOns\TradeSkillMaster\Core\UI\CraftingUI\Core.lua:155: in function `callback'
...erface\AddOns\TradeSkillMaster\LibTSM\Util\Event.lua:85: in function `ProcessEvent'
...erface\AddOns\TradeSkillMaster\LibTSM\Util\Event.lua:101: in function <...erface\AddOns\TradeSkillMaster\LibTSM\Util\Event.lua:93>

Locals:

**Comment by Gethe** [comment]
I just tested this, and couldn't replicate it. Are you still getting it? If so, does it happen with TSM disabled?
