### ISSUE TITLE
[Feature] Option to remove help system toggle button from frames

### ISSUE THREAD

**Issue by ultrasn0w** [Haleth/Aurora#241]
**Is your feature request related to a problem? Please describe.**
Not related to a functional problem.

**Describe the solution you'd like**
Add an option to hide the orange _i_ Blizzard help system toggle button for all restyled frames.

**Describe alternatives you've considered**
Searching for another way to hide the Blizzard help system toggle button.

**Additional context**
![Wow_2020-11-08_14-04-27](https://user-images.githubusercontent.com/10564498/98465745-5b5f9300-21cb-11eb-9dba-c5ece446affa.png)

Is this possible? Or are those buttons not accessible?
It would improve the "clean" design of all frames.

Thanks for the nice addon.

**Comment by Gethe** [comment]
I don't want Aurora to get too bogged down with options, so I try to keep it to things that would create significant conflict with other addons. (e.g. action bars or tooltips)
