### ISSUE TITLE
[Bug] error on opening EncounterJournal

### ISSUE THREAD

**Issue by Medivha** [Haleth/Aurora#242]
**Describe the bug**
everytime i open the Encounterjournal for the first time

Message: Interface\AddOns\Aurora\Skin\backdrop.lua:585: attempt to index local 'frame' (a nil value)
Time: Tue Nov 17 08:40:46 2020
Count: 1
Stack: Interface\AddOns\Aurora\Skin\backdrop.lua:585: attempt to index local 'frame' (a nil value)
[string "@Interface\AddOns\Aurora\Skin\backdrop.lua"]:585: in function `SetBackdrop'
[string "@Interface\AddOns\Aurora\Skin\AddOns\Blizzard_EncounterJournal.lua"]:136: in function `EJButtonTemplate'
[string "@Interface\AddOns\Aurora\Skin\AddOns\Blizzard_EncounterJournal.lua"]:569: in function `addonModule'
[string "@Interface\AddOns\Aurora\Skin\init.lua"]:246: in function <Interface\AddOns\Aurora\Skin\init.lua:210>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
[string "@Interface\FrameXML\UIParent.lua"]:661: in function `EncounterJournal_LoadUI'
[string "@Interface\FrameXML\UIParent.lua"]:1045: in function `ToggleEncounterJournal'
[string "@Interface\FrameXML\MainMenuBarMicroButtons.lua"]:1209: in function <Interface\FrameXML\MainMenuBarMicroButtons.lua:1207>
[string "=[C]"]: ?

Locals: frame = nil
color = <table> {
 colorStr = "ff3f3f3f"
 b = 0.250000
 Lightness = <function> defined @Interface\AddOns\Aurora\Skin\color.lua:71
 g = 0.250000
 GetRGBA = <function> defined @Interface\SharedXML\Color.lua:28
 Saturation = <function> defined @Interface\AddOns\Aurora\Skin\color.lua:65
 SetRGB = <function> defined @Interface\SharedXML\Color.lua:43
 Hue = <function> defined @Interface\AddOns\Aurora\Skin\color.lua:59
 GetRGB = <function> defined @Interface\SharedXML\Color.lua:20
 r = 0.250000
 GenerateHexColorMarkup = <function> defined @Interface\SharedXML\Color.lua:51
 WrapTextInColorCode = <function> defined @Interface\SharedXML\Color.lua:55
 GenerateHexColor = <function> defined @Interface\SharedXML\Color.lua:47
 IsEqualTo = <function> defined @Interface\AddOns\Aurora\Skin\color.lua:42
 isAchromatic = true
 SetRGBA = <function> defined @Interface\AddOns\Aurora\Skin\color.lua:29
 OnLoad = <function> defined @Interface\SharedXML\Color.lua:9
 GetRGBAsBytes = <function> defined @Interface\SharedXML\Color.lua:24
 GetRGBAAsBytes = <function> defined @Interface\SharedXML\Color.lua:32
}
alpha = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'frame' (a nil value)"
Base = <table> {
 SetHighlight = <function> defined @Interface\AddOns\Aurora\Skin\deprecated.lua:13
 SetTexture = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:214
 SetFont = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:90
 IsTextureRegistered = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:210
 SetBackdropColor = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:591
 SetBackdrop = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:584
 CropIcon = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:78
 GetAddonSkins = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:55
 AddSkin = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:39
 CreateBackdrop = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:565
 RegisterTexture = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:224
}
backdrop = <table> {
 bgFile = "Interface\Buttons\WHITE8x8"
 tile = true
 backdropBorderSubLevel = -7
 offsets = <table> {
 }
 backdropSubLevel = -8
 edgeFile = "Interface\Buttons\WHITE8x8"
 backdropBorderLayer = "BACKGROUND"
 backdropLayer = "BACKGROUND"
 edgeSize = 1
 insets = <table> {
 }
}

**Expected behavior**
no error ;)

**Screenshots**

**Additional context**
its on the german client so idk if its relevant
testet with other addons and testet with other addons deactivated
retail wow
bug is happening for a while now

**Comment by liquidbase** [comment]
Same issue here. The error message appears once after every login or reload.

**Comment by Gethe** [comment]
The lastest release is intended for, and primarily tested on 9.0.2. If your client doesn't have that yet I would wait.

**Comment by Medivha** [comment]
can comfirm eu is now on 9.0.2 and the error doesnt appear anymore
