### ISSUE TITLE
Dressing Room Window [Bug]

### ISSUE THREAD

**Issue by 3urodancer** [Haleth/Aurora#243]
Dressing Room Window panel

As of the recent update, the Dressing Room Panel alignment is off. See screenshots below. 

**AURORA ENABLED**
![Capture](https://user-images.githubusercontent.com/74639023/99481328-1e0bab80-2917-11eb-826a-4fc7c10e3ac3.PNG)

**AURORA DISABLED**
![image](https://user-images.githubusercontent.com/74639023/99481444-65923780-2917-11eb-8d37-76b1ece57cbe.png)

**Comment by cargol31** [comment]
Bug also encountered

**Comment by zofia1347** [comment]
I also have this bug!
