### ISSUE TITLE
[Bug] Retail Errors when killing any endboss in a dungeon

### ISSUE THREAD

**Issue by Medivha** [Haleth/Aurora#249]
**Describe the bug**
2 error messages when finishing the endboss of a dungeon (i guess something with the you finished the dungeon popup)

**To Reproduce**
everytime on the end of a dungeon

**Expected behavior**
no error

**Additional context**
error 1

Message: ...ce\AddOns\Aurora\Skin\FrameXML\AlertFrameSystems.lua:69: attempt to index field 'dungeonArt1' (a nil value)
Time: Tue Dec  1 07:43:36 2020
Count: 1
Stack: ...ce\AddOns\Aurora\Skin\FrameXML\AlertFrameSystems.lua:69: attempt to index field 'dungeonArt1' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Aurora\Skin\FrameXML\AlertFrameSystems.lua"]:69: in function `?'
[string "@Interface\AddOns\Aurora\Skin\SharedXML\Pools.lua"]:20: in function <Interface\AddOns\Aurora\Skin\SharedXML\Pools.lua:13>
[string "@Interface\AddOns\Aurora\Skin\SharedXML\Pools.lua"]:37: in function <Interface\AddOns\Aurora\Skin\SharedXML\Pools.lua:31>
[string "=[C]"]: in function `Acquire'
[string "@Interface\FrameXML\AlertFrames.lua"]:164: in function `ShowAlert'
[string "@Interface\FrameXML\AlertFrames.lua"]:113: in function `AddAlert'
[string "@Interface\FrameXML\AlertFrames.lua"]:502: in function <Interface\FrameXML\AlertFrames.lua:501>
[string "=[C]"]: in function `xpcall'
[string "@Interface\FrameXML\ObjectAPI\ContinuableContainer.lua"]:76: in function `CheckIfSatisifed'
[string "@Interface\FrameXML\ObjectAPI\ContinuableContainer.lua"]:44: in function `ContinueOnLoad'
[string "@Interface\FrameXML\AlertFrames.lua"]:501: in function <Interface\FrameXML\AlertFrames.lua:461>

Locals: 

error 2

Message: ...ce\AddOns\Aurora\Skin\FrameXML\AlertFrameSystems.lua:330: attempt to index field '_title' (a nil value)
Time: Tue Dec  1 08:06:50 2020
Count: 1
Stack: ...ce\AddOns\Aurora\Skin\FrameXML\AlertFrameSystems.lua:330: attempt to index field '_title' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\Aurora\Skin\FrameXML\AlertFrameSystems.lua"]:330: in function `?'
[string "@Interface\AddOns\Aurora\Skin\FrameXML\AlertFrames.lua"]:16: in function <...nterface\AddOns\Aurora\Skin\FrameXML\AlertFrames.lua:14>
[string "=[C]"]: in function `AddAlertFrame'
[string "@Interface\FrameXML\AlertFrames.lua"]:184: in function `ShowAlert'
[string "@Interface\FrameXML\AlertFrames.lua"]:113: in function `AddAlert'
[string "@Interface\FrameXML\AlertFrames.lua"]:492: in function <Interface\FrameXML\AlertFrames.lua:491>
[string "=[C]"]: in function `xpcall'
[string "@Interface\FrameXML\ObjectAPI\ContinuableContainer.lua"]:76: in function `CheckIfSatisifed'
[string "@Interface\FrameXML\ObjectAPI\ContinuableContainer.lua"]:27: in function <...nterface\FrameXML\ObjectAPI\ContinuableContainer.lua:25>
[string "=[C]"]: in function `xpcall'
[string "@Interface\FrameXML\ObjectAPI\AsyncCallbackSystem.lua"]:76: in function `FireCallbacks'
[string "@Interface\FrameXML\ObjectAPI\AsyncCallbackSystem.lua"]:35: in function <Interface\FrameXML\ObjectAPI\AsyncCallbackSystem.lua:31>

Locals: 

not sure if they are both from the same dungeon despite the timestamp but it had 2 errors listet so i post them both

**Comment by Gethe** [comment]
fixed in 6009f39f
