### ISSUE TITLE
[Bug] Null LUA Error

### ISSUE THREAD

**Issue by Jeremy7600** [Haleth/Aurora#251]
**Describe the bug**
Null LUA Error

**To Reproduce**
1. Go to EPL.
2. Change area so that the title appears on screen, eg: Lights Hope Chapel
3. See error

**Expected behavior**
No Error

Error log:
Message: ...ace\AddOns\Aurora\Skin\AddOns\Blizzard_UIWidgets.lua:19: attempt to index field 'widgetFrames' (a nil value)
Time: Sat Dec  5 11:05:49 2020
Count: 2
Stack: ...ace\AddOns\Aurora\Skin\AddOns\Blizzard_UIWidgets.lua:19: attempt to index field 'widgetFrames' (a nil value)
...ace\AddOns\Aurora\Skin\AddOns\Blizzard_UIWidgets.lua:19: in function <...ace\AddOns\Aurora\Skin\AddOns\Blizzard_UIWidgets.lua:15>
[C]: in function `CreateWidget'
...dOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:259: in function `ProcessWidget'
...dOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:315: in function `ProcessWidgetSet'
...dOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:340: in function `UpdateAllWidgets'
...dOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:33: in function <...dOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:31>

Locals: self = UIWidgetManager {
 0 = <userdata>
 UpdateWidget = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:321
 EnumerateWidgetsByWidgetTag = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:423
 UnregisterWidgetSetContainer = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:393
 timerWidgets = <table> {
 }
 ProcessWidgetSet = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:312
 layoutUpdateSetsPending = <table> {
 }
 OnUpdate = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:39
 RegisterWidgetSetContainer = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:373
 widgetVisTypeInfo = <table> {
 }
 UpdateTimerList = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:74
 registeredWidgetSetContainers = <table> {
 }
 AddWidgetToWidgetTagList = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:106
 widgetTagToFrames = <table> {
 }
 IsWidgetTypeSupported = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:201
 widgetIdToFrame = <table> {
 }
 numTimers = 0
 widgetPools = <table> {
 }
 UpdateAllWidgets = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:329
 CreateWidget = <function> defined =[C]:-1
 RemoveWidgetFromWidgetTagList = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:124
 ReleaseAllWidgets = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:54
 OnLoad = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:11
 RemoveAllWidgetsInWidgetSet = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:167
 widgetTagToNumFrames = <table> {
 }
 RegisterWidgetVisTypeTemplate = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:404
 ProcessWidget = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:235
 ScheduleUpdateWidgetSetLayout = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:228
 GetWidgetFromPools = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:62
 widgetSetFrames = <table> {
 }
 UpdateWidgetSetContainerLayout = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:217
 RemoveWidget = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:183
 OnEvent = <function> defined @Interface\AddOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:31
}
widgetID = 1896
widgetSetID = 1
widgetType = 0
template = "UIWidgetTemplateIconAndText"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'widgetFrames' (a nil value)"
Skin = <table> {
 ExpandOrCollapse = <function> defined @Interface\AddOns\Aurora\Skin\SharedXML\SharedUIPanelTemplates

**Additional context**
This only started happening with the Scourge Invasion. Any time you change subzones the error pops up.

**Comment by Gethe** [comment]
is this in classic?

**Comment by Jeremy7600** [comment]
Yes it is Classic, sorry I didn't mention that. Latest Aurora.
