### ISSUE TITLE
[Bug] Retail map background/buttons

### ISSUE THREAD

**Issue by retraenn** [Haleth/Aurora#252]
**Describe the bug**
The map background, close, and minimize button are not correctly positioned after opening the map for the first time on the latest update. Opening the Quest log once appears to fix this issue completely until /reload.

**To Reproduce**
1. Open the World Map

**Expected behavior**
--

**Screenshots**
Before opening the Quest Log
https://i.imgur.com/Hgg1E2Z.jpg

After opening the Quest Log:
https://i.imgur.com/V4yt11k.jpg

**Additional context**
I'm using 'Leatrix maps' addon which changes the layout of the map slightly for my screenshot but this issue wasn't present until the latest update for Aurora and the issue is present even with Leatrix maps disabled.

**Comment by Gethe** [comment]
I'm not seeing this issue. Do you have any other addons affecting the map? Have you tried with only Aurora enabled?

**Comment by retraenn** [comment]
With every addon except Aurora disabled this is the result I get following the same steps are my original post:
Before:
https://i.imgur.com/h7F9Z6H.jpg

After:
https://i.imgur.com/aOVQJVy.jpg

The close/minimize buttons move and the 'Maps' logo appears.

Sorry for not testing with all addons disabled to begin with by the way, should've been the first thing I did.
