### ISSUE TITLE
[Bug] Achievement Panel Display Issue

### ISSUE THREAD

**Issue by Epidemdabear** [Haleth/Aurora#255]
When using the search box on the Achievement Panel the resulting dropdown selection box is extremely hard to see / read, can its background be made solid so it can be read?

![Screenshot 2021-01-06 144003](https://user-images.githubusercontent.com/60220665/103780936-93e5e680-502d-11eb-9b54-a6072f7ec55a.png)

**Comment by Gethe** [comment]
Fixed in 5427eaa18ce162126a52bd7c40f5e1dcb265d38f
