### ISSUE TITLE
[Bug] TBC pre-patch broke it completely

### ISSUE THREAD

**Issue by InfernalDark** [Haleth/Aurora#267]
Not working at all.

**Comment by Nabohs** [comment]
Error code taken from Swatter:

Date: 2021-05-28 00:50:49
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Aurora\Skin\util.lua line 155:
   hooksecurefunc(): SetBorder is not a function
Debug:
   [string "=[C]"]: hooksecurefunc()
   [string "@Aurora\Skin\util.lua"]:155: Mixin()
   [string "@Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua"]:451: PortraitFrameTemplateNoCloseButton()
   [string "@Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua"]:470: PortraitFrameTemplate()
   [string "@Aurora\Skin\SharedXML\SharedUIPanelTemplates.lua"]:476: ButtonFrameTemplate()
   [string "@Aurora\Skin\deprecated.lua"]:309: ReskinPortraitFrame()
   [string "@Aurora\Skin\AddOns\Blizzard_TimeManager.lua"]:26: addonModule()
   [string "@Aurora\Skin\init.lua"]:247:
      Aurora\Skin\init.lua:211
Locals:

AddOns:
  Swatter, v1.13.6652 (SwimmingSeadragon)
  AdiBags, vDEV
  AdiBagsItemRackSets, vv1.7
  AdvancedInterfaceOptions, v1.5.0-1-gcd568fb
  Atlas, vv1.49.00
  AtlasBurningCrusade, vv1.49.00
  AtlasClassicWoW, vv1.49.00
  AtlasLootClassic, vv2.2.0-bcc
  AtlasLootClassicData, vv2.2.0-bcc
  AtlasLootClassicDungeonsAndRaids, vv2.2.0-bcc
  Attune, v227
  AucAdvanced, v1.13.6686 (SwimmingSeadragon)
  AucFilterBasic, v1.13.6680 (SwimmingSeadragon)
  AucStatHistogram, v1.13.6681 (SwimmingSeadragon)
  AucStatiLevel, v1.13.6636 (SwimmingSeadragon)
  AucStatPurchased, v1.13.6672 (SwimmingSeadragon)
  AucStatSimple, v1.13.6634 (SwimmingSeadragon)
  AucStatStdDev, v1.13.6635 (SwimmingSeadragon)
  AucUtilFixAH, v1.13.6608 (SwimmingSeadragon)
  Auctionator, v100.0.11
  Aurora, v9.0.2.1
  AutoVendor, v68-classic
  BeanCounter, v1.13.6682 (SwimmingSeadragon)
  BlizzMove, vv3.0.18
  CEPGP, v
  ClassicAuraDurations, v1.13.65
  ClassicCastbars, vv1.4.0
  ClassicCastbarsOptions, vv1.4.0
  DBMAceAttorneyMusicPack, v1.0.0
  DBMCore, v2.5.4
  DBMStatusBarTimers, v
  DBMVPHazelNutty, v1.1
  Details, v
  DetailsTinyThreat, v
  Dominos, v9.0.28
  DominosCast, v
  DominosEncounter, v
  DominosProgress, v
  DominosRoll, v
  ElkBuffBars, v2.6.2-199
  Enchantrix, v1.13.6662 (SwimmingSeadragon)
  EnchantrixBarker, v1.13.6692 (SwimmingSeadragon)
  Gnosis, vr241
  Immersion, v1.3.7
  ItemRack, v
  ItemTooltipProfessionIcons, v1.2
  KuiMedia, v
  KuiNameplates, v2.27.3a
  KuiNameplatesCore, v
  LeatrixMaps, v2.5.37
  LeatrixPlus, v2.5.37
  Masque, v9.0.6
  MasqueSerenity, v9.0.7
  MaxCam, v2.5.1
  MBB, v1.2.0
  MikScrollingBattleText, v5.7.152
  NovaInstanceTracker, v1.17
  NovaWorldBuffs, v2.06
  OmniCC, v9.0.10
  Postal, vr436
  Prat30, v3.9.1-1-g6978fc8
  Prat30Libraries, v
  Questie, v6.3.13
  SexyMap, vv3-bcc
  SlideBar, v1.13.6668 (SwimmingSeadragon)
  Stubby, v1.13.6614 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v2.5.1.20501 <none>
  (ck=78c)

**Comment by MightBeChris** [comment]
Still at it.  I could post the same error but it's above.  The dif is no other addons loaded.
