### ISSUE TITLE
[Bug] (TBC Classic) Options appearing but no changes are being made

### ISSUE THREAD

**Issue by Nabohs** [Haleth/Aurora#268]
Error pulled from Swatter

Date: 2021-06-03 11:51:21
ID: 5
Error occured in: Global
Count: 1
Message: ..\AddOns\Aurora\gui.lua line 155:
   attempt to index local 'value' (a boolean value)
Debug:
   [string "@Aurora\gui.lua"]:155:
      Aurora\gui.lua:149
Locals:
self = <unnamed> {
 BottomLeftCorner = <unnamed> {
 }
 OnBackdropLoaded = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:178
 GetBackdropColor = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:272
 SetBackdropOptions = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:344
 value = "customHighlight"
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 GetBackdropTexture = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:320
 ApplyBackdrop = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:189
 SetBackdrop = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:233
 ClearBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:369
 GetBackdropBorderColor = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:292
 GetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:434
 SetBackdropGradient = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:298
 SetBorderBlendMode = <function> defined @Interface\SharedXML\Backdrop.lua:353
 SetBackdropOption = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:329
 SetBackdropLayer = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:306
 backdropInfo = <table> {
 }
 OnBackdropSizeChanged = <function> defined @Interface\SharedXML\Backdrop.lua:269
 TopRightCorner = <unnamed> {
 }
 GetBackdropOption = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:338
 GetEdgeSize = <function> defined @Interface\SharedXML\Backdrop.lua:275
 Center = <unnamed> {
 }
 TopEdge = <unnamed> {
 }
 _backdropInfo = <table> {
 }
 0 = <userdata>
 BottomEdge = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
 GetBackdropLayer = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:315
 SetupTextureCoordinates = <function> defined @Interface\SharedXML\Backdrop.lua:301
 HasBackdropInfo = <function> defined @Interface\SharedXML\Backdrop.lua:365
 SetupPieceVisuals = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:181
 SetBackdropColor = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:262
 LeftEdge = <unnamed> {
 }
 SetBackdropBorderColor = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:276
}
value = true
(*temporary) = <table> {
 swatchFunc = <function> defined @Interface\AddOns\Aurora\gui.lua:118
 cancelFunc = <function> defined @Interface\AddOns\Aurora\gui.lua:134
}
(*temporary) = <table> {
 swatchFunc = <function> defined @Interface\AddOns\Aurora\gui.lua:118
 cancelFunc = <function> defined @Interface\AddOns\Aurora\gui.lua:134
}
(*temporary) = <table> {
 swatchFunc = <function> defined @Interface\AddOns\Aurora\gui.lua:118
 cancelFunc = <function> defined @Interface\AddOns\Aurora\gui.lua:134
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'value' (a boolean value)"
swatch = <unnamed> {
 BottomLeftCorner = <unnamed> {
 }
 OnBackdropLoaded = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:178
 GetBackdropColor = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:272
 SetBackdropOptions = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:344
 value = "customHighlight"
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 GetBackdropTexture = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:320
 ApplyBackdrop = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:189
 SetBackdrop = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:233
 ClearBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:369
 GetBackdropBorderColor = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:292
 GetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:434
 SetBackdropGradient = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:298
 SetBorderBlendMode = <function> defined @Interface\SharedXML\Backdrop.lua:353
 SetBackdropOption = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:329
 SetBackdropLayer = <function> defined @Interface\AddOns\Aurora\Skin\back
AddOns:
  Swatter, v1.13.6652 (SwimmingSeadragon)
  AdiBags, vv1.9.24-bcc
  AdiBagsItemRackSets, vv1.7
  AdvancedInterfaceOptions, v1.5.0-1-gcd568fb
  Atlas, vv1.49.00
  AtlasBurningCrusade, vv1.49.00
  AtlasClassicWoW, vv1.49.00
  AtlasLootClassic, vv2.2.1-bcc
  AtlasLootClassicData, vv2.2.1-bcc
  AtlasLootClassicDungeonsAndRaids, vv2.2.1-bcc
  Attune, v227
  AucAdvanced, v1.13.6686 (SwimmingSeadragon)
  AucFilterBasic, v1.13.6680 (SwimmingSeadragon)
  AucStatHistogram, v1.13.6681 (SwimmingSeadragon)
  AucStatiLevel, v1.13.6636 (SwimmingSeadragon)
  AucStatPurchased, v1.13.6672 (SwimmingSeadragon)
  AucStatSimple, v1.13.6634 (SwimmingSeadragon)
  AucStatStdDev, v1.13.6635 (SwimmingSeadragon)
  AucUtilFixAH, v1.13.6608 (SwimmingSeadragon)
  Auctionator, v100.0.11
  Aurora, v9.0.5.0
  AutoCarrot, v1.13.12
  AutoVendor, v68-classic
  BeanCounter, v1.13.6682 (SwimmingSeadragon)
  BlizzMove, vv3.0.18
  CEPGP, v
  ClassicAuraDurations, v2.5.4
  ClassicCastbars, vv1.4.0
  ClassicCastbarsOptions, vv1.4.0
  DBMAceAttorneyMusicPack, v1.0.0
  DBMCore, v2.5.4
  DBMStatusBarTimers, v
  DBMVPHazelNutty, v1.1
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Dominos, v9.0.28
  DominosCast, v
  DominosEncounter, v
  DominosProgress, v
  DominosRoll, v
  ElkBuffBars, v2.6.2-199
  Enchantrix, v1.13.6662 (SwimmingSeadragon)
  EnchantrixBarker, v1.13.6692 (SwimmingSeadragon)
  Gnosis, vr241
  Immersion, v1.3.7
  Informant, v1.13.6684 (SwimmingSeadragon)
  ItemRack, v
  ItemTooltipProfessionIcons, v1.2
  KuiMedia, v
  KuiNameplates, v2.27.3a
  KuiNameplatesCore, v
  LeatrixMaps, v2.5.38
  LeatrixPlus, v2.5.38
  Masque, v9.0.6
  MasqueSerenity, v9.0.7
  MaxCam, v2.5.1
  MBB, v1.2.0
  MikScrollingBattleText, v5.7.152
  NovaInstanceTracker, v1.17
  NovaWorldBuffs, v2.08
  OmniCC, v9.0.10
  Postal, vr436
  Prat30, v3.9.1
  Prat30Libraries, v
  Questie, v6.3.14
  RepByZone, v1.19.5
  SexyMap, vv3-bcc
  ShadowedUnitFrames, vv4.3.1-classic-1-gf597a16
  SheepMonitor, v1.23
  SinStats, v3.1.7
  SlideBar, v1.13.6668 (SwimmingSeadragon)
  SpellbookAbridged, v2.6.4a
  Stubby, v1.13.6614 (SwimmingSeadragon)
  TipTac, v21.05.26
  TipTacItemRef, v21.05.11
  TranqRotate, v1.7.0
  WeakAuras, v3.4.2
  WeakAurasCompanion, v1.1.0
  WeaponSwingTimer, v6.3.4
  WowUp, v1.0.0
  wowupdataaddon, v1.0.0
  BlizRuntimeLib_enUS v2.5.1.20501 <none>
  (ck=925)

**Comment by Gethe** [comment]
I can't replicate this error. Try disabling your other addons, there may be a conflict.

**Comment by Nabohs** [comment]
disabled all Addons except for Aurora, received the following Error in chat:

ERROR: Interface/AddOns/Aurora/aurora.lua87: attempt to index field 'customHighlight' (a boolean value)

**Comment by Gethe** [comment]
probably the saved vars file was corrupted somehow

**Comment by Nabohs** [comment]
tried that, not working after renaming and deleting. Looks like the Custom Highlight Color in the options might be causing an issue. Enabled Swatter for the error file:

Date: 2021-06-03 13:33:30
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Aurora\gui.lua line 280:
   attempt to index field 'customHighlight' (a boolean value)
Debug:
   [string "@Aurora\gui.lua"]:280:
      Aurora\gui.lua:274
Locals:
self = <unnamed> {
 0 = <userdata>
 Text = AuroraOptionsText {
 }
 value = "customHighlight"
}
(*temporary) = true
(*temporary) = <unnamed> {
 0 = <userdata>
 Text = AuroraOptionsText {
 }
 value = "customHighlight"
}
(*temporary) = false
(*temporary) = "attempt to index field 'customHighlight' (a boolean value)"
highlightButton = <unnamed> {
 BottomLeftCorner = <unnamed> {
 }
 OnBackdropLoaded = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:178
 GetBackdropColor = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:272
 SetBackdropOptions = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:344
 value = "customHighlight"
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 GetBackdropTexture = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:320
 ApplyBackdrop = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:189
 SetBackdrop = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:233
 ClearBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:369
 GetBackdropBorderColor = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:292
 GetBackdrop = <function> defined @Interface\SharedXML\Backdrop.lua:434
 SetBackdropGradient = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:298
 SetBorderBlendMode = <function> defined @Interface\SharedXML\Backdrop.lua:353
 SetBackdropOption = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:329
 SetBackdropLayer = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:306
 backdropInfo = <table> {
 }
 OnBackdropSizeChanged = <function> defined @Interface\SharedXML\Backdrop.lua:269
 TopRightCorner = <unnamed> {
 }
 GetBackdropOption = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:338
 GetEdgeSize = <function> defined @Interface\SharedXML\Backdrop.lua:275
 Center = <unnamed> {
 }
 TopEdge = <unnamed> {
 }
 _backdropInfo = <table> {
 }
 0 = <userdata>
 BottomEdge = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
 GetBackdropLayer = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:315
 SetupTextureCoordinates = <function> defined @Interface\SharedXML\Backdrop.lua:301
 HasBackdropInfo = <function> defined @Interface\SharedXML\Backdrop.lua:365
 SetupPieceVisuals = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:181
 SetBackdropColor = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:262
 LeftEdge = <unnamed> {
 }
 SetBackdropBorderColor = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:276
}
private = <table> {
 isPatch = false
 disabled = <table> {
 }
 uiScale = 1
 API_MINOR = 8
 IGNORED_QUEST_DISPLAY = "|cffbfbfbf%s (ignored)|r"
 isBCC = true
 TRIVIAL_QUEST_DISPLAY = "|cffbfbfbf%s (low level)|r"
 textures = <table> {
 }
 classColorsReset = <function> defined @Interface\AddOns\Aurora\Skin\color.lua:360
 debug = <function> defined @Interface\AddOns\Aurora\Skin\init.lua:79
 charClass = <table> {
 }
 fileOrder = <table> {
 }
 backdrop = <table> {
 }
 UpdateUIScale = <function> defined @Interface\AddOns\Aurora\Skin\init.lua:29
 FACTION_COLORS = <table> {
 }
 SharedXML = <table> {
 }
 setColorCache = <function> defined @Interface\AddOns\Aurora\Skin\color.lua:353
 updateHighlightColor = <function> defined @Interface\AddOns\Aurora\aurora.lua:85
 isClassic = false
 API_MAJOR = 0
 nop = <function> defined @Interface\AddOns\Aurora\Skin\init.lua:79
 OnLoad = <function> defined @Interface\AddOns\Aurora\aurora.lua:38
 commands = <table> {
 }
 SetupGUI = <function> defined @Interface\AddOns\Aurora\gui.lua:377
 FrameXML = <table> {
 }
 isRetail = false
 AddOns = <table> {
 }
 atlasColors = <table> {
 }
 NORMAL_QUEST_DISPLAY = "|cffffffff%s|r"
 Enum = <table> {
 }
 FRAME_TITLE_HEIGHT = 27
 Aurora = <table> {
 }
 font = <table> {
 }
}

AddOns:
  Swatter, v1.13.6652 (SwimmingSeadragon)
  Aurora, v9.0.5.0
  BlizRuntimeLib_enUS v2.5.1.20501 <none>
  (ck=67)

**Comment by Nabohs** [comment]
Solved the issue, a secondary SavedVariables file was being generated for each character (along with the solo Account Name SavedVariables file). Did a fresh delete of the entire backup .Lua files and that fixed the issue
