### ISSUE TITLE
Skin addon detection

### ISSUE THREAD

**Issue by Gethe** [Haleth/Aurora#28]
So I was thinking of ways to make the style addons not need to be loaded before Aurora. It occurred to me that a variation on how DBM handles its bar skin API would probably work pretty well.

The basic idea is that any addon that wants to define a style will have Aurora listed as a dependency. This way we know when each addon will load relative to each other. When Aurora loads, it will iterate all addons and look for a special tag (eg. X-Aurora), then store the associated addon. When the stored addon loads, Aurora then applies the changes it may have.

In order to prevent graphical incongruities, if a StyleAddOn exists Aurora would have to defer doing any UI changes until after the style gets loaded.

I made some example code:

``` lua
-- Aurora stuff

local StyleAddOn
for i = 1, GetNumAddOns() do
    if GetAddOnMetadata(i, "X-Aurora") then
        StyleAddOn = GetAddOnInfo(i)
    end
end

-- Other Aurora stuff

local function applyStyle()
    -- apply the style
end

local Skin = CreateFrame("Frame", nil, UIParent)
Skin:RegisterEvent("ADDON_LOADED")
Skin:SetScript("OnEvent", function(self, event, addon)
    if addon == "Aurora" and not StyleAddOn then
        --[[ only apply the style here if there is not a StyleAddOn, since doing so might
           make things inconsistent.]]
        applyStyle()
    elseif StyleAddOn and addon == StyleAddOn then
        -- init custom style
        applyStyle()
    end
end)
```

I haven't made any of these changes yet, let alone tests, but regardless I wanted to see what you thought about it.

**Comment by Haleth** [comment]
This looks pretty good actually, hadn't thought of doing things this way. I'll see if I can get this working.
