### ISSUE TITLE
[Bug] Addon not working with Character, Skill or Talent Windows

### ISSUE THREAD

**Issue by Nabohs** [Haleth/Aurora#283]
**Describe the bug**
Addon is not working with the Character, Quest Log, Spellbook or Talent Screens, options have been excluded from /aurora panel

**Screenshots**
Please see screenshot
![image](https://user-images.githubusercontent.com/84953472/131594801-5726872f-0bab-4911-83a0-7909037cccfe.png)

**Comment by Nabohs** [comment]
Received an error code when Talents were opened:

Date: 2021-08-31 21:00:22
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Aurora\Skin\backdrop.lua line 603:
   attempt to index local 'frame' (a nil value)
Debug:
   [string "@Aurora\Skin\backdrop.lua"]:603: SetBackdrop()
   [string "@Aurora\aurora.lua"]:117: FrameTypeFrame()
   [string "@Aurora\Skin\AddOns\Blizzard_TalentUI.lua"]:34: addonModule()
   [string "@Aurora\Skin\init.lua"]:248:
      Aurora\Skin\init.lua:212
   [string "=[C]"]: LoadAddOn()
   [string "@Interface_TBC\FrameXML\UIParent.lua"]:364: UIParentLoadAddOn()
   [string "@Interface_TBC\FrameXML\UIParent.lua"]:427: TalentFrame_LoadUI()
   [string "@Interface_TBC\FrameXML\UIParent.lua"]:512: ToggleTalentFrame()
   [string "TOGGLETALENTS"]:1:
      [string "TOGGLETALENTS"]:1
Locals:
frame = nil
color = <table> {
 a = 0.200000
 colorStr = "ff000000"
 b = 0
 Lightness = <function> defined @Interface\AddOns\Aurora\Skin\color.lua:71
 g = 0
 GetRGBA = <function> defined @Interface_TBC\SharedXML\Util.lua:378
 Saturation = <function> defined @Interface\AddOns\Aurora\Skin\color.lua:65
 SetRGB = <function> defined @Interface_TBC\SharedXML\Util.lua:393
 Hue = <function> defined @Interface\AddOns\Aurora\Skin\color.lua:59
 GetRGB = <function> defined @Interface_TBC\SharedXML\Util.lua:370
 r = 0
 GenerateHexColorMarkup = <function> defined @Interface_TBC\SharedXML\Util.lua:401
 WrapTextInColorCode = <function> defined @Interface_TBC\SharedXML\Util.lua:405
 GenerateHexColor = <function> defined @Interface_TBC\SharedXML\Util.lua:397
 IsEqualTo = <function> defined @Interface\AddOns\Aurora\Skin\color.lua:42
 isAchromatic = true
 SetRGBA = <function> defined @Interface\AddOns\Aurora\Skin\color.lua:29
 OnLoad = <function> defined @Interface_TBC\SharedXML\Util.lua:359
 GetRGBAsBytes = <function> defined @Interface_TBC\SharedXML\Util.lua:374
 GetRGBAAsBytes = <function> defined @Interface_TBC\SharedXML\Util.lua:382
}
alpha = 0.500000
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'frame' (a nil value)"
Base = <table> {
 SetHighlight = <function> defined @Interface\AddOns\Aurora\Skin\deprecated.lua:13
 SetTexture = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:214
 SetFont = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:90
 IsTextureRegistered = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:210
 SetBackdropColor = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:609
 SetBackdrop = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:602
 CropIcon = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:78
 GetAddonSkins = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:55
 AddSkin = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:39
 CreateBackdrop = <function> defined @Interface\AddOns\Aurora\Skin\backdrop.lua:583
 RegisterTexture = <function> defined @Interface\AddOns\Aurora\Skin\api.lua:224
}
backdrop = <table> {
 bgFile = "Interface\Buttons\WHITE8x8"
 tile = true
 backdropBorderSubLevel = -7
 offsets = <table> {
 }
 backdropSubLevel = -8
 edgeFile = "Interface\Buttons\WHITE8x8"
 backdropBorderLayer = "BACKGROUND"
 backdropLayer = "BACKGROUND"
 edgeSize = 1
 insets = <table> {
 }
}

AddOns:
  Swatter, v1.13.6652 (SwimmingSeadragon)
  AdiBags, vv1.9.25-bcc
  AdvancedInterfaceOptions, v1.6.0
  Atlas, vv1.49.01
  AtlasBurningCrusade, vv1.49.00
  AtlasClassicWoW, vv1.49.00
  AtlasLootClassic, vv2.3.2-bcc
  AtlasLootClassicData, vv2.3.2-bcc
  AtlasLootClassicDungeonsAndRaids, vv2.3.2-bcc
  Attune, v242
  AucAdvanced, v1.13.6707 (SwimmingSeadragon)
  AucFilterBasic, v1.13.6680 (SwimmingSeadragon)
  AucStatHistogram, v1.13.6681 (SwimmingSeadragon)
  AucStatiLevel, v1.13.6705 (SwimmingSeadragon)
  AucStatPurchased, v1.13.6672 (SwimmingSeadragon)
  AucStatSimple, v1.13.6634 (SwimmingSeadragon)
  AucStatStdDev, v1.13.6635 (SwimmingSeadragon)
  AucUtilFixAH, v1.13.6608 (SwimmingSeadragon)
  Auctionator, v100.0.11
  Aurora, v9.0.5.0
  AutoVendor, v68-classic
  BeanCounter, v1.13.6682 (SwimmingSeadragon)
  BetterVendorPrice, vv1.15.01
  BlizzMove, vv3.1.3
  CEPGP, v
  CEPGPTBC, v1.0.2
  ClassicAuraDurations, v2.5.5
  ClassicCastbars, vv1.4.0
  ClassicCastbarsOptions, vv1.4.0
  DBMAceAttorneyMusicPack, v1.0.0
  DBMCore, v2.5.11
  DBMSMGEventsPack, v1.5.13
  DBMSoundEventsPack, v1.6.12
  DBMStatusBarTimers, v
  DBMVPHazelNutty, v1.1
  Details, v
  DetailsTinyThreat, v
  Dominos, v9.1.0
  DominosCast, v
  DominosEncounter, v
  DominosProgress, v
  DominosRoll, v
  ElkBuffBars, v2.6.2-199
  Enchantrix, v1.13.6662 (SwimmingSeadragon)
  EnchantrixBarker, v1.13.6692 (SwimmingSeadragon)
  GatherMate2, v1.46.1-classic
  Gnosis, vr241
  Immersion, v1.3.7
  Informant, v1.13.6684 (SwimmingSeadragon)
  ItemTooltipProfessionIcons, v1.2
  LeatrixMaps, v2.5.54
  LeatrixPlus, v2.5.54
  LFGBulletinBoard, v2.59
  MagicMarker, v9.0.5
  MagicMarkerData, v1.0
  MaxCam, v2.5.1
  MBB, v1.2.0
  MikScrollingBattleText, v5.7.152
  NovaInstanceTracker, v1.21
  NovaWorldBuffs, v2.14
  Objection, v0.0.6
  OmniCC, v9.1.0
  Postal, vv3.7.2bcc
  Prat30, v3.9.1
  Prat30Libraries, v
  Puggle, v216
  Questie, v6.5.1
  RatingBuster, v
  RepByZone, v1.19.7
  SexyMap, vv5-bcc
  ShadowedUnitFrames, vv4.3.1-classic-2-g9302929
  SheepMonitor, v1.23
  SinStats, v3.5.8
  SpellbookAbridged, v2.6.4a
  Stubby, v1.13.6614 (SwimmingSeadragon)
  TidyPlatesThreatPlates, v10.2.11
  TipTac, v21.05.26
  TipTacItemRef, v21.05.11
  TitanClassic, v1.3.4.20501
  TitanClassicAmmo, v1.3.4.20501
  TitanClassicBag, v1.3.4.20501
  TitanClassicClock, v1.3.4.20501
  TitanClassicGold, v1.3.4.20501
  TitanClassicLocation, v1.3.4.20501
  TitanClassicLootType, v1.3.4.20501
  TitanClassicPerformance, v1.3.4.20501
  TitanClassicRegen, v1.3.4.20501
  TitanClassicRepair, v1.3.4.20501
  TitanClassicVolume, v1.3.4.20501
  TitanClassicXP, v1.3.4.20501
  WeakAuras, v3.7.0
  WeakAurasCompanion, v1.1.0
  WeaponSwingTimer, v6.5.1
  WowUp, v1.0.3
  wowupdataaddon, v1.0.3
  XLoot, v9.0-8
  XLootFrame, v9.0-8
  XLootGroup, v9.0-8
  XLootMaster, v9.0-8
  XLootMonitor, v9.0-8
  BlizRuntimeLib_enUS v2.5.2.20502 <none>
  (ck=b47)

**Comment by Jeremy7600** [comment]
change all instances of  _G.TalentFrame* to _G.PlayerTalentFrame* in Aurora\Skin\AddOns\Blizzard_TalentUI.lua (this is a bug I've been dealing with myself) And by change all I mean change all, even the ones like _G.TalentFrameTab1, etc. They all need to say _G.PlayerTalentFrame(something) except the first one.  

(line 70) _G["TalentFrameBackground"..name] needs to be: _G["PlayerTalentFrameBackground"..name] 

(line 114) Skin.TalentButtonTemplate(_G["TalentFrameTalent"..i]) needs to be: Skin.TalentButtonTemplate(_G["PlayerTalentFrameTalent"..i])

delete your WTF\Account\<AccountName>\SavedVariables\Aurora.lua file, that will get the rest working and you'll have to reconfigure your preferences in the addon panel.

**Comment by Nabohs** [comment]
> change all instances of _G.TalentFrame* to _G.PlayerTalentFrame* in Aurora\Skin\AddOns\Blizzard_TalentUI.lua (this is a bug I've been dealing with myself) And by change all I mean change all, even the ones like _G.TalentFrameTab1, etc. They all need to say _G.PlayerTalentFrame(something) except the first one.
> 
> (line 70) _G["TalentFrameBackground"..name] needs to be: _G["PlayerTalentFrameBackground"..name]
> 
> (line 114) Skin.TalentButtonTemplate(_G["TalentFrameTalent"..i]) needs to be: Skin.TalentButtonTemplate(_G["PlayerTalentFrameTalent"..i])
> 
> delete your WTF\Account<AccountName>\SavedVariables\Aurora.lua file, that will get the rest working and you'll have to reconfigure your preferences in the addon panel.

That worked, now trying to figure out the issue for a lot of the other screens, but I can't tell from the file names, need to do some more digging
