### ISSUE TITLE
Totally broken after 9.1.5

### ISSUE THREAD

**Issue by hobulian** [Haleth/Aurora#285]
Literally. It doesn't function at all

**Comment by Gethe** [comment]
Not constructive or helpful

**Comment by hobulian** [comment]
Thanks. Will released for 9.1.5?

**Comment by hobulian** [comment]
> Not constructive or helpful

Is this addon now under maintenance? Hope will be updated soon..

**Comment by biomhold** [comment]
For me, too, after 9.1.5, nothing works, I don't know how to find the problem
![image](https://user-images.githubusercontent.com/94900490/143014019-afe2a520-0552-4cda-b1b1-e67c377ec34a.png)
