### ISSUE TITLE
Quest text color

### ISSUE THREAD

**Issue by Zalkin** [Haleth/Aurora#31]
In my quest log the text is litterally black on black. Is this a bug and is there a way to fix it ? I tried reinstalling both Aurora and the missing textures multiple times. Tried deleting folders and altering the coding but nothing have seemed to work :( pls this is really annoying me.
![22bf15b22e6c2b0c20a2133b2cf514b0](https://cloud.githubusercontent.com/assets/13203438/8525652/800e55fa-2402-11e5-92b4-985578fd2257.jpg)

**Comment by Haleth** [comment]
I haven't seen this myself. Does this only happen in the Darkmoon Faire or is it the same for every kind of dialog frame?

http://puu.sh/j60bq/4a73529657.png

**Comment by Zalkin** [comment]
Happened at every dialog i went to.

**Comment by Gethe** [comment]
This is fairly old and I haven't seen this issue in my tests, so i'm going to close this for now. If you are still getting this somewhere, please reply with additional info and screenshots.
