### ISSUE TITLE
Lua Error and Black QuestWindow Text

### ISSUE THREAD

**Issue by xanui** [Haleth/Aurora#33]
Hi! 
I get a Lua Error since the patch today when I log in.

18x Aurora\aurora-6.3b.lua:2187: attempt to index global 'HelpFrameTicket' (a nil value)
Aurora\aurora-6.3b.lua:2187: in function <Aurora\aurora.lua:698>

Furthermore some "Quest Window Interaction Options" are Black now.
I think the Issue was mentioned earlier.

At last, thank you for this grad AddOn, please keep up the good work!

**Comment by Haleth** [comment]
4e8dc3576e5913b9c94424122b49d49e50ec61d6 does this fix it?

**Comment by xanui** [comment]
yeah it did, tank you! i observed another issue: i cant see the buttons in the ready check window.
But i don't know if this problem is caused by aurora oder aurora missing textures or anything else
