### ISSUE TITLE
Trade skill reagent icon

### ISSUE THREAD

**Issue by solor** [Haleth/Aurora#49]
![1](https://cloud.githubusercontent.com/assets/156806/17652614/af182312-62b3-11e6-8b22-c6f60c5174d5.jpg)

**Comment by Gethe** [comment]
I have not seen this literally at all. Are you using an icon replacement pack? Blizzard made some changes to how textures load, and it may affect those packs.

**Comment by solor** [comment]
@Gethe Yes, I use clean icon pack, I'll test it later without icon replacement, thanks for infomation.

**Comment by solor** [comment]
looks like it's not aurora's problem.

**Comment by solor** [comment]
sorry for bring this again, but im sure it's aurora's problem, not icon replacement side.
