### ISSUE TITLE
Feature Request: Enable "travelPassButton" (Invite Button) again.

### ISSUE THREAD

**Issue by mtthsw** [Haleth/Aurora#50]
Hey, 

I wanted to ask, if it's possible to enable the travelPassButton again in the FriendsFrame. Was there a reason, why you disabled it?

I "hotfixed" it myself ... I want to update the addon in the future. Maybe this snippet could minimize the work for that feature. I only miss some kind of an info when the button is disabled.

Aurora.lua; Line 145+

			--bu.travelPassButton:SetAlpha(0)
			--bu.travelPassButton:EnableMouse(false)
			F.Reskin(bu.travelPassButton)
			bu.travelPassButton:SetSize(22, 22)
			
			local inv = bu.travelPassButton:CreateFontString(nil, 'OVERLAY')
			inv:SetFont([[Fonts/ARIALN.ttf]], 14)
			inv:SetPoint('CENTER', bu.travelPassButton, 0, 0)
			inv:SetText('+')
			inv:SetSize(22,22)
			inv:SetJustifyH('CENTER')
			inv:SetTextColor(1, 1, 1)
			inv:SetShadowOffset(.7, -.7)
			inv:SetShadowColor(0, 0, 0, 1)

... and inside the UpdateScroll() function

			-- change the SetPoint
			bu.gameIcon:SetPoint("TOPRIGHT", bu, "TOPRIGHT", -24, -1)

Hope you consider it! If not, it's okay, tho.

**Comment by Gethe** [comment]
I can't comment on why it was disabled, since i'm obviously not the one who wrote it. That said I have had this modification in RealUI for a while, I just haven't got around to merging in some of those changes.

**Comment by siweia** [comment]
Haleth said the icon is ugly and useless, and that's why he removed.
