### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by melicon** [Haleth/Aurora#59]
Hello there...
Fresh download new to the addon but it does not do/skin anything and has errors

Message: Interface\AddOns\Aurora\gui.lua:227: attempt to index field 'AuroraConfig' (a nil value)
Time: 08/24/16 16:21:51
Count: 1
Stack: Interface\AddOns\Aurora\gui.lua:227: in function <Interface\AddOns\Aurora\gui.lua:226>

**Comment by Gethe** [comment]
Fixed in commit 8854e3aeb8a6078d90a1d65aeef122fb4d44e150
