### ISSUE TITLE
how did I fix it?

### ISSUE THREAD

**Issue by goodoopoo** [Haleth/Aurora#62]
Message: Interface\AddOns\Aurora\aurora.lua:125: attempt to index upvalue 'AuroraConfig' (a nil value)
Time: 08/27/16 12:03:54
Count: 1
Stack: Interface\AddOns\Aurora\aurora.lua:125: in function `CreateBD'
...terface\AddOns\Aurora\AddOns\Blizzard_DebugTools.lua:15: in function `addonModule'
Interface\AddOns\Aurora\aurora.lua:836: in function <Interface\AddOns\Aurora\aurora.lua:731>
[C]: in function `LoadAddOn'
[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:7: in function <[string "Interface\FrameXML\BasicControls.xml:<Scrip..."]:4>
[C]: ?
...e\AddOns\Aurora\AddOns\Blizzard_ItemAlterationUI.lua:3: in main chunk

Locals: f = ScriptErrorsFrame {
 0 = <userdata>
 warnType = <table> {
 }
 messages = <table> {
 }
 close = <unnamed> {
 }
 previous = <unnamed> {
 }
 indexLabel = <unnamed> {
 }
 reload = <unnamed> {
 }
 locals = <table> {
 }
 title = <unnamed> {
 }
 times = <table> {
 }
 seen = <table> {
 }
 count = <table> {
 }
 order = <table> {
 }
 next = <unnamed> {
 }
}
a = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = ScriptErrorsFrame {
 0 = <userdata>
 warnType = <table> {
 }
 messages = <table> {
 }
 close = <unnamed> {
 }
 previous = <unnamed> {
 }
 indexLabel = <unnamed> {
 }
 reload = <unnamed> {
 }
 locals = <table> {
 }
 title = <unnamed> {
 }
 times = <table> {
 }
 seen = <table> {
 }
 count = <table> {
 }
 order = <table> {
 }
 next = <unnamed> {
 }
}
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'AuroraConfig' (a nil value)"
C = <table> {
 defaults = <table> {
 }
 classcolours = <table> {
 }
 media = <table> {
 }
 TOC = 70000
 frames = <table> {
 }
 themes = <table> {
 }
}
AuroraConfig = nil
_G = <table> {
 ERR_OUT_OF_CHI = "真气不足"
 DH_HAVOC_CORE_ABILITY_2 = "强大的近战攻击，消耗恶魔之怒。如果攻击造成爆击，将恢复部分恶魔之怒。"
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "彩色标记单位名。"
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 736
 EventTraceFrameButton7HideButton = EventTraceFrameButton7HideButton {
 }
 SPELL_FAILED_CUSTOM_ERROR_71 = "这名聚会者想要和你一起跳舞。"
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 395
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture = CompactUnitFrameProfilesGeneralOptionsFrameHealthTextDropdownButtonNormalTexture {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "你无法交易已经装备的包裹。"
 PVP_RANK_6_1 = "下士"
 BOOKTYPE_PROFESSION = "professions"
 AudioOptionsVoicePanelOutputDeviceDropDownButtonHighlightTexture = AudioOptionsVoicePanelOutputDeviceDropDownButtonHighlightTexture {
 }
 VideoOptionsFrameCategoryFrameButton17ToggleHighlightTexture = VideoOptionsFrameCategoryFrameButton17ToggleHighlightTexture {
 }
 MerchantItem2AltCurrencyFrameItem1Text = MerchantItem2AltCurrencyFrameItem1Text {
 }
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "在按下快捷键时施法，而不是在松开快捷键时施法。"
 BINDING_NAME_NAMEPLATES = "显示敌方姓名板"
 CHAT_HEADER_SUFFIX = ": "
 IsReferAFriendLinked = <function> defined =[C]:-1
 MAIL_LETTER_TOOLTIP = "点击这里来获得一份这封信
永久性的副本。"
 AudioOptionsVoicePanelMicrophoneVolumeThumb = AudioOptionsVoicePanelMicrophoneVolumeThumb {
 }
 PaperDollTitlesPaneButton14BgTop = PaperDollTitlesPaneButton14BgTop {
 }
 DUNGEON_FLOOR_UPPERBLACKROCKSPIRE3 = "黑手大厅"
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 FCFDockOverflowButton_OnClick = <function> defined @Interface\FrameXML\FloatingChatFrame.lua:2337
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 ChatFrame6EditBoxFocusMid = ChatFrame6EditBoxFocusMid {
 }
 BN_UNABLE_TO_RESOLVE_NAME = "无法向'%s'发送悄悄话。战网功能也许暂时不可用。"
 LE_GAME_ERR_RECRUIT_A_FRIEND_FAILED = 941
 CompactRaidFrameManagerDisplayFrameHiddenModeToggleTopRight = CompactRaidFrameManage

**Comment by Gethe** [comment]
Should be fixed with 7.0.6
