### ISSUE TITLE
Profession Materials Icon Issue

### ISSUE THREAD

**Issue by mottaflm** [Haleth/Aurora#64]
Hello there,

I found an issue where icons from materials in professions interface are all black :(

![iconsissue](https://cloud.githubusercontent.com/assets/21315200/18070395/8491a82a-6e1b-11e6-9342-41087ba2ff1a.png)

It can load after they appear as black for the first time and you reload your interface. But this doesn't apply for all materials, just the ones you just viewed.

Thank you!

**Comment by B0N3** [comment]
Having the same issue. I tried deleting WoWs cache folder, but it didn't help.

**Comment by Almerish** [comment]
I have the same issue. Seems to be fixed by disabling Aurora's tooltip option (at least it is for me).

**Comment by vekspec** [comment]
still having the issue even with version 7.1.1. deleting cache sometimes fixes it. i will see if tooltip option works.

**Comment by solor** [comment]
temporary solution

edit this file 
```Aurora\AddOns\Blizzard_TradeSkillUI.lua```

delete line 131
```F.ReskinIcon(reagent.Icon)```
