### ISSUE TITLE
Chatbubble font to big in dungeons

### ISSUE THREAD

**Issue by TalasNetrag** [Haleth/Aurora#82]
Everytime I join a dungeon, the font in the speech boxes gets really big and stays that way after the dengeon. The only way to reset is /relaod.

**Comment by Gethe** [comment]
I made some tweaks to the chat bubble skin. Let me know if you are still getting this issue.

**Comment by TalasNetrag** [comment]
The issue is still present, but now it returns to normal after the dungeon.

Here's how it looks outside and in a dungeon. (With Aurora Missing Textures)
<a href="http://www.directupload.net/file/d/4856/cda2avmm_png.htm" target="_blank"><img src="http://fs5.directupload.net/images/170925/temp/cda2avmm.png" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>

Here only Aurora is enabled with default settings.
<a href="http://www.directupload.net/file/d/4856/9s8q6fkb_png.htm" target="_blank"><img src="http://fs5.directupload.net/images/170925/temp/9s8q6fkb.png" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>
It looks like there a no skins aplied in the dungeon for the chatbubble.

Version 7.3.0.4

**Comment by Gethe** [comment]
Blizzard has made modifications to speach bubbles forbidden while in dungeons or raids, similar to friendly nameplates. There is nothing I can do about it.
