### ISSUE TITLE
Don't show a popup message every time I reload the UI.

### ISSUE THREAD

**Issue by Industrial** [Haleth/Aurora#83]
Being an addon developer, this does not work.

Please add a checkbox to this popup to never show it again and an option in the options menu to undo that choice.

It would be very much appreciated ;) i remember people made addons specifically to filter out "welcome" messages in the chat window for a good reason..

**Comment by Gethe** [comment]
Clicking "Got it" instead of close should make it not show again.

**Comment by Industrial** [comment]
lol, wow.. >_<
