### ISSUE TITLE
Flickering arrow buttons

### ISSUE THREAD

**Issue by Wdavis4692** [Haleth/Aurora#86]
experiencing flickering arrow buttons.  Notably any UI arrow element such as on the quest text screen, world map pane drop down menus, etc. The white arrows flicker. The video makes it look less noticeable than it actually is. This is with NO other addons running at all. It's just Aurora! (note: I re-enabled the addons before recording the following video though)

Here is the shareable link to the video demonstrating the problem:

https://drive.google.com/open?id=0B7vKk67D3QUKeDNuN3ZyUEVfdHM

The flickering becomes FAR worse if refresh rate is set to 60 Hz.  Changing to fullscreen windowed or normal fullscreen makes no difference, though all arrow buttons become blank prior to a UI reload after doing this. 

There are no .lua errors popping up.  Seems to be a graphical thing.  Either a loop in code causing the whites of the arrows to constantly hide and refresh, or two textures vying for superiority on the same spot?

EDIT:  The problem also exists with the reputation bars in the factions UI panel:

https://drive.google.com/open?id=0B7vKk67D3QUKZEVRNktMazU1WWs

**Comment by Clagein** [comment]
This is happening to me as well. Replicates with a fresh install when aurora is enabled. Issue first arose with build 7.3.0.1 and persists into 7.3.0.2. My achievement bars are also affected. Like the above poster, no LUA errors are generated.

**Comment by Gethe** [comment]
I haven't seen this issue at all while making this update. The nature of it makes me think it may be related to a bug detailed [here](http://www.wowinterface.com/forums/showthread.php?p=324831), in which case there may not be much I can do for it.

That said I'll see if I can come up with a solution.

**Comment by ceesco53** [comment]
@Wdavis4692 @Clagein @Gethe  I have this issue as well.  My solution may work for you:  I stop the flickering by changing to Windowed Fullscreen mode then back to Fullscreen mode.

**Comment by VaporAPX** [comment]
This issue still happens for me.  I was hoping it was going to be resolved in an update since it's fairly old but I've just gotten used to it.  Today I did some digging and it seems that when I run my computer on SLI mode, the flickering is there, and off a single card the flickering is gone and everything is as normal.  

Not sure if this is similar to the people who have posted here but I thought I'd bring this up again to see if it can be addressed.  Thanks for your time, love the addon!

**Comment by Cinnamilk** [comment]
I'm also getting this flickering on all button textures, to the point that it's too distracting to keep Aurora enabled.

**Comment by Gethe** [comment]
I've made some changes in 8.0.1.7 that may help. If your still getting this issue, please open a new one.
