### ISSUE TITLE
Mythic+ End frame background

### ISSUE THREAD

**Issue by blockberd** [Haleth/Aurora#94]
Hi,
the background image of the Mythic+ end frame seems... wrong. No idea how I could fix that.

See https://i.imgur.com/Pam2f46.png

**Comment by Gethe** [comment]
Are you using any texture replacement packs?

**Comment by blockberd** [comment]
I'm sorry. I just found out this came from the "Challenges" texture from Tonyleila's "Aurora: Missing Textures" pack. I deleted that and it solved the issue.

Again, I'm sorry.
