### ISSUE TITLE
Personal Resource

### ISSUE THREAD

**Issue by Abiz901** [Haleth/Aurora#98]
Hello. 

Within WoW's Interface > Names, there is an option to toggle a Personal Resource Display on/off.

With Aurora enabled, each time I do a reloadui, the option is automatically toggled on.  I wish to have it off, yet it returns each time I reload.  This only occurs when the Aurora addon is enabled.

Is this something I can fix?  

Many thanks in advance.

**Comment by Gethe** [comment]
Does this happen even with *only* Aurora enabled? I am not seeing this behavior.

**Comment by Abiz901** [comment]
Yes, although I've found a workaround of setting the CVar alpha to 0 for now, so I don't have any issue anymore.  Thanks.
